<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
$id=max(0,(int)($_GET['id']??0));
$stmt=db()->prepare("SELECT c.*,d.name_de AS atoll_de,d.name_en AS atoll_en,d.intro_de AS atoll_intro_de,d.intro_en AS atoll_intro_en,d.latitude,d.longitude,d.code AS atoll_code FROM catalog_items c JOIN destinations d ON d.id=c.destination_id WHERE c.id=? AND c.type='accommodation' AND c.active=1 AND c.maldives_available=1 AND d.active=1 AND d.country_code='MV' LIMIT 1");
$stmt->execute([$id]);$resort=$stmt->fetch();
if(!$resort){http_response_code(404);$pageTitle=t('Resort nicht gefunden','Resort not found');require __DIR__.'/includes/public-header.php';echo '<main class="success-page"><section class="success-card"><h1>'.e($pageTitle).'</h1><a class="button button-dark" href="'.e(url('maldives.php?lang='.lang())).'">'.e(t('Zu den Resorts','View resorts')).'</a></section></main>';require __DIR__.'/includes/public-footer.php';exit;}
$mealStmt=db()->prepare('SELECT * FROM accommodation_meal_plans WHERE catalog_item_id=? AND active=1 ORDER BY sort_order,id');$mealStmt->execute([$id]);$mealPlans=$mealStmt->fetchAll();
$serviceStmt=db()->prepare("SELECT * FROM catalog_items WHERE destination_id=? AND type IN ('service','activity','sight','restaurant','spice_garden','shop') AND maldives_available=1 AND active=1 ORDER BY type,featured DESC,sort_order,id");$serviceStmt->execute([$resort['destination_id']]);$services=$serviceStmt->fetchAll();
$typeLabels=['service'=>t('Transfer / Leistung','Transfer / service'),'activity'=>t('Aktivität','Activity'),'sight'=>t('Ausflug','Excursion'),'restaurant'=>t('Restaurant','Restaurant'),'spice_garden'=>t('Gewürzgarten','Spice garden'),'shop'=>t('Shop','Shop')];
$pageTitle=$resort['name_'.lang()];$bodyClass='resort-page';$extraStyles=['css/maldives.css'];require __DIR__.'/includes/public-header.php';
$hero=$resort['image_path']?url($resort['image_path']):asset('images/hero.jpg');
?>
<main>
    <section class="resort-hero" style="background-image:linear-gradient(90deg,rgba(7,39,42,.95),rgba(7,39,42,.35)),url('<?= e($hero) ?>')"><div><p class="eyebrow"><?= e($resort['atoll_'.lang()]) ?> · <?= e($resort['meta_'.lang()]) ?></p><h1><?= e($resort['name_'.lang()]) ?></h1><span><?= e($resort['description_'.lang()]) ?></span><div><a class="button button-gold" href="<?= e(url('stay.php?type=maldives&hotel='.(int)$resort['id'].'&lang='.lang())) ?>"><?= e(t('Dieses Resort auswählen','Choose this resort')) ?> <b>→</b></a><a class="quiet-resort-link" href="<?= e(url('maldives.php?lang='.lang())) ?>"><?= e(t('Alle Resorts','All resorts')) ?></a></div></div><aside><small><?= e(t('Richtpreis ab','Guide rate from')) ?></small><strong><?= e(money(price_with_markup($resort['price_per_person']))) ?></strong><span><?= e(t('pro Doppelzimmer / Nacht','per double room / night')) ?></span></aside></section>
    <section class="resort-intro"><div><p class="eyebrow dark"><?= e(t('ATOLL & RESORT','ATOLL & RESORT')) ?></p><h2><?= e($resort['atoll_'.lang()]) ?></h2><p><?= e($resort['atoll_intro_'.lang()]) ?></p></div><dl><div><dt><?= e(t('Standardbelegung','Standard occupancy')) ?></dt><dd><?= (int)$resort['standard_room_guests'] ?> <?= e(t('Gäste','guests')) ?></dd></div><div><dt><?= e(t('Maximal mit Zusatzbett','Maximum with extra bed')) ?></dt><dd><?= (int)$resort['max_guests_with_extra_bed'] ?> <?= e(t('Gäste','guests')) ?></dd></div><div><dt><?= e(t('Zusatzbett','Extra bed')) ?></dt><dd><?= e(number_format((float)$resort['extra_bed_percent'],0,',','.')) ?> %</dd></div><div><dt><?= e(t('Kinderpreis','Child rate')) ?></dt><dd><?= e(number_format((float)$resort['child_percent'],0,',','.')) ?> %</dd></div></dl></section>
    <section class="resort-options"><article><p class="eyebrow dark"><?= e(t('VERPFLEGUNG','MEAL PLANS')) ?></p><h2><?= e(t('Wählen Sie passend zu Ihrem Aufenthalt.','Choose what suits your stay.')) ?></h2><div class="resort-option-list"><?php foreach($mealPlans as $plan):?><div><span><?= e($plan['name_'.lang()]) ?></span><strong><?= (float)$plan['supplement_per_person_night']>0?'+ '.e(money(price_with_markup($plan['supplement_per_person_night']))).' / '.e(t('Person/Nacht','person/night')):e(t('ohne Zuschlag','no supplement')) ?></strong></div><?php endforeach;?></div></article><article><p class="eyebrow dark"><?= e(t('TRANSFERS & ERLEBNISSE','TRANSFERS & EXPERIENCES')) ?></p><h2><?= e(t('Optional ergänzbar.','Available as options.')) ?></h2><div class="resort-option-list"><?php foreach($services as $service):?><div><span><small><?= e($typeLabels[$service['type']]??$service['type']) ?></small><?= e($service['name_'.lang()]) ?></span><strong><?= e(money(price_with_markup($service['price_per_person']))) ?> · <?= e(stay_price_basis_label($service['price_basis'])) ?></strong></div><?php endforeach;?></div></article></section>
    <section class="resort-cta"><div><p class="eyebrow"><?= e(t('UNVERBINDLICHE ANFRAGE','NO-OBLIGATION ENQUIRY')) ?></p><h2><?= e(t('Zimmer, Verpflegung und Transfers zusammenstellen.','Build your room, meal plan and transfers.')) ?></h2></div><a class="button button-gold" href="<?= e(url('stay.php?type=maldives&hotel='.(int)$resort['id'].'&lang='.lang())) ?>"><?= e(t('Resorturlaub planen','Plan resort holiday')) ?> <b>→</b></a></section>
</main>
<?php require __DIR__.'/includes/public-footer.php';?>
