<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require_portal_user();
$id=(int)($_GET['id']??0);
$stmt=db()->prepare('SELECT b.*,r.reference,r.request_type,r.customer_name,r.customer_email,r.travelers,r.duration,r.estimate,r.hotel_name_de,r.hotel_name_en FROM bookings b JOIN tour_requests r ON r.id=b.request_id WHERE b.id=?');
$stmt->execute([$id]);$booking=$stmt->fetch();
if(!$booking||!portal_can_access_booking($booking)){http_response_code(403);exit('Access denied');}
$paymentStmt=db()->prepare('SELECT * FROM booking_payments WHERE booking_id=? ORDER BY payment_date DESC,id DESC');$paymentStmt->execute([$id]);$payments=$paymentStmt->fetchAll();
$user=portal_user();$isAgent=$user['user_type']==='agent';$balance=max(0,(float)$booking['total_amount']-(float)$booking['paid_amount']);
$statusLabels=['provisional'=>t('Vorläufig','Provisional'),'confirmed'=>t('Bestätigt','Confirmed'),'in_progress'=>t('Reise läuft','In progress'),'completed'=>t('Abgeschlossen','Completed'),'cancelled'=>t('Storniert','Cancelled')];
$paymentLabels=['unpaid'=>t('Offen','Unpaid'),'partial'=>t('Teilbezahlt','Part-paid'),'paid'=>t('Bezahlt','Paid'),'refunded'=>t('Erstattet','Refunded')];
$methodLabels=['bank_transfer'=>t('Überweisung','Bank transfer'),'card'=>t('Karte','Card'),'paypal'=>'PayPal','cash'=>t('Bar','Cash'),'other'=>t('Sonstige','Other')];
$isHotel=in_array($booking['request_type'],['beach','ayurveda','maldives'],true);
$pageTitle=t('Buchung','Booking').' '.$booking['booking_reference'];$bodyClass='account-page';$extraStyles=['css/account.css'];
require dirname(__DIR__).'/includes/public-header.php';$accountPage='dashboard';require __DIR__.'/_nav.php';
?>
<main class="account-main"><a class="account-back" href="<?= e(url('account/index.php?lang='.lang())) ?>">← <?= e(t('Zur Übersicht','Back to overview')) ?></a>
<section class="account-heading compact"><div><p><?= e(t('BUCHUNG','BOOKING')) ?> · <?= e($booking['booking_reference']) ?></p><h1><?= e($booking['customer_name']) ?></h1><span><?= e($statusLabels[$booking['status']]??$booking['status']) ?> · <?= e($paymentLabels[$booking['payment_status']]??$booking['payment_status']) ?></span></div><a class="account-primary inline" target="_blank" href="<?= e(url(($isHotel?'stay-proposal.php':'itinerary.php').'?ref='.urlencode($booking['reference']))) ?>"><?= e(t('Reisedokument drucken','Print travel document')) ?> ⌁</a></section>
<section class="account-stat-grid booking"><article><small><?= e(t('Gesamtbetrag','Total')) ?></small><strong><?= e(money_precise($booking['total_amount'])) ?></strong><span>EUR</span></article><article><small><?= e(t('Bezahlt','Paid')) ?></small><strong><?= e(money_precise($booking['paid_amount'])) ?></strong><span><?= e($paymentLabels[$booking['payment_status']]??'') ?></span></article><article><small><?= e(t('Offener Betrag','Balance')) ?></small><strong><?= e(money_precise($balance)) ?></strong><span><?= $booking['payment_due_date']?e(t('fällig am ','due ').date('d.m.Y',strtotime($booking['payment_due_date']))):e(t('kein Fälligkeitsdatum','no due date')) ?></span></article><article><small><?= e(t('Reisebeginn','Start date')) ?></small><strong class="date"><?= $booking['travel_start_date']?e(date('d.m.Y',strtotime($booking['travel_start_date']))):e(t('Flexibel','Flexible')) ?></strong><span><?= (int)$booking['duration'] ?> <?= e(t('Nächte','nights')) ?></span></article></section>
<div class="account-detail-grid"><section class="account-card"><header><div><h2><?= e(t('Zahlungsverlauf','Payment history')) ?></h2><p><?= e(t('Vom Reiseveranstalter erfasste Zahlungen.','Payments recorded by the tour operator.')) ?></p></div></header><?php if(!$payments):?><div class="account-empty small"><?= e(t('Noch keine Zahlung erfasst.','No payment has been recorded yet.')) ?></div><?php else:?><div class="account-payments"><?php foreach($payments as $payment):?><article><div><strong><?= e($methodLabels[$payment['payment_method']]??$payment['payment_method']) ?></strong><small><?= e(date('d.m.Y',strtotime($payment['payment_date']))) ?><?= $payment['transaction_reference']?' · '.e($payment['transaction_reference']):'' ?></small></div><b><?= e(money_precise($payment['amount'])) ?></b></article><?php endforeach;?></div><?php endif;?></section><aside class="account-side"><section class="account-card account-info"><h2><?= e(t('Buchungsdaten','Booking details')) ?></h2><dl><dt><?= e(t('Anfragereferenz','Enquiry reference')) ?></dt><dd><a href="<?= e(url('account/request.php?id='.(int)$booking['request_id'])) ?>"><?= e($booking['reference']) ?></a></dd><dt><?= e(t('Status','Status')) ?></dt><dd><?= e($statusLabels[$booking['status']]??'') ?></dd><dt><?= e(t('Reisende','Travellers')) ?></dt><dd><?= (int)$booking['travelers'] ?></dd><?php if($isAgent):?><dt><?= e(t('Provision','Commission')) ?></dt><dd><?= e(number_format((float)$booking['agent_commission_percent'],2,',','.')) ?> % · <?= e(money_precise($booking['agent_commission_amount'])) ?></dd><?php endif;?></dl></section><?php if($booking['customer_notes']):?><section class="account-card account-info"><h2><?= e(t('Hinweis zur Buchung','Booking note')) ?></h2><p><?= nl2br(e($booking['customer_notes'])) ?></p></section><?php endif;?></aside></div></main>
<?php require dirname(__DIR__).'/includes/public-footer.php';?>
