CREATE TABLE IF NOT EXISTS admin_users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin','editor') NOT NULL DEFAULT 'admin',
    active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS destinations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    country_code CHAR(2) NOT NULL DEFAULT 'LK',
    slug VARCHAR(140) NOT NULL UNIQUE,
    code VARCHAR(8) NOT NULL,
    name_de VARCHAR(180) NOT NULL,
    name_en VARCHAR(180) NOT NULL,
    region_de VARCHAR(180) NOT NULL DEFAULT '',
    region_en VARCHAR(180) NOT NULL DEFAULT '',
    intro_de TEXT NOT NULL,
    intro_en TEXT NOT NULL,
    default_nights TINYINT UNSIGNED NOT NULL DEFAULT 2,
    price_from DECIMAL(10,2) NOT NULL DEFAULT 0,
    accent VARCHAR(30) NOT NULL DEFAULT 'leaf',
    image_path VARCHAR(255) NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    google_place_id VARCHAR(255) NOT NULL DEFAULT '',
    sort_order INT NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_destinations_active_sort (active, sort_order),
    INDEX idx_destinations_country (country_code, active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_classifications (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    item_type VARCHAR(40) NOT NULL,
    code VARCHAR(80) NOT NULL,
    name_de VARCHAR(160) NOT NULL,
    name_en VARCHAR(160) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_catalog_classification (item_type, code),
    INDEX idx_catalog_classification_type (item_type, active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    destination_id INT UNSIGNED NOT NULL,
    type ENUM('accommodation','sight','activity','restaurant','spice_garden','shop','service') NOT NULL,
    classification_id INT UNSIGNED NULL,
    star_rating TINYINT UNSIGNED NOT NULL DEFAULT 0,
    market_segment VARCHAR(30) NOT NULL DEFAULT '',
    sltda_registration_number VARCHAR(120) NOT NULL DEFAULT '',
    sltda_registration_expiry DATE NULL,
    name_de VARCHAR(190) NOT NULL,
    name_en VARCHAR(190) NOT NULL,
    description_de TEXT NOT NULL,
    description_en TEXT NOT NULL,
    meta_de VARCHAR(255) NOT NULL DEFAULT '',
    meta_en VARCHAR(255) NOT NULL DEFAULT '',
    facilities_de TEXT NOT NULL,
    facilities_en TEXT NOT NULL,
    opening_hours_de VARCHAR(255) NOT NULL DEFAULT '',
    opening_hours_en VARCHAR(255) NOT NULL DEFAULT '',
    duration_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    booking_required TINYINT(1) NOT NULL DEFAULT 0,
    supplier_name VARCHAR(190) NOT NULL DEFAULT '',
    supplier_contact TEXT NOT NULL,
    contract_price DECIMAL(10,2) NOT NULL DEFAULT 0,
    commission_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    internal_notes TEXT NOT NULL,
    price_per_person DECIMAL(10,2) NOT NULL DEFAULT 0,
    price_basis ENUM('per_person','per_person_night','per_booking','free','on_request') NOT NULL DEFAULT 'per_person',
    beach_available TINYINT(1) NOT NULL DEFAULT 0,
    ayurveda_available TINYINT(1) NOT NULL DEFAULT 0,
    maldives_available TINYINT(1) NOT NULL DEFAULT 0,
    standard_room_guests TINYINT UNSIGNED NOT NULL DEFAULT 2,
    max_guests_with_extra_bed TINYINT UNSIGNED NOT NULL DEFAULT 3,
    extra_bed_percent DECIMAL(5,2) NOT NULL DEFAULT 30.00,
    child_percent DECIMAL(5,2) NOT NULL DEFAULT 50.00,
    child_max_age TINYINT UNSIGNED NOT NULL DEFAULT 12,
    ayurveda_night_options VARCHAR(80) NOT NULL DEFAULT '7,14,21,28',
    image_path VARCHAR(255) NULL,
    featured TINYINT(1) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_catalog_destination FOREIGN KEY (destination_id) REFERENCES destinations(id) ON DELETE CASCADE,
    INDEX idx_catalog_destination_type (destination_id, type, active, sort_order),
    INDEX idx_catalog_classification_id (classification_id),
    INDEX idx_catalog_maldives (maldives_available, active, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accommodation_meal_plans (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    catalog_item_id INT UNSIGNED NOT NULL,
    code VARCHAR(40) NOT NULL,
    name_de VARCHAR(120) NOT NULL,
    name_en VARCHAR(120) NOT NULL,
    supplement_per_person_night DECIMAL(10,2) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_meal_plan_accommodation FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE,
    UNIQUE KEY uq_accommodation_meal_plan (catalog_item_id, code),
    INDEX idx_meal_plan_item_active_sort (catalog_item_id, active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name_de VARCHAR(120) NOT NULL,
    name_en VARCHAR(120) NOT NULL,
    capacity SMALLINT UNSIGNED NOT NULL,
    price_per_day_with_driver DECIMAL(10,2) NOT NULL DEFAULT 0,
    self_drive_allowed TINYINT(1) NOT NULL DEFAULT 0,
    price_per_day_without_driver DECIMAL(10,2) NOT NULL DEFAULT 0,
    driver_price_per_km DECIMAL(10,2) NOT NULL DEFAULT 0.30,
    image_path VARCHAR(255) NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_vehicles_active_capacity (active, capacity, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS guides (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    guide_code VARCHAR(40) NOT NULL UNIQUE,
    status ENUM('pending','approved','suspended','rejected') NOT NULL DEFAULT 'pending',
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    display_name VARCHAR(190) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(80) NOT NULL DEFAULT '',
    whatsapp VARCHAR(80) NOT NULL DEFAULT '',
    date_of_birth DATE NULL,
    gender VARCHAR(40) NOT NULL DEFAULT '',
    nationality VARCHAR(100) NOT NULL DEFAULT '',
    address TEXT NOT NULL,
    city VARCHAR(120) NOT NULL DEFAULT '',
    district VARCHAR(120) NOT NULL DEFAULT '',
    country VARCHAR(120) NOT NULL DEFAULT 'Sri Lanka',
    nic_passport VARCHAR(120) NOT NULL DEFAULT '',
    license_number VARCHAR(120) NOT NULL DEFAULT '',
    license_type VARCHAR(120) NOT NULL DEFAULT '',
    license_expiry DATE NULL,
    tourism_registration VARCHAR(120) NOT NULL DEFAULT '',
    years_experience TINYINT UNSIGNED NOT NULL DEFAULT 0,
    languages VARCHAR(500) NOT NULL DEFAULT '',
    service_regions VARCHAR(500) NOT NULL DEFAULT '',
    specializations VARCHAR(500) NOT NULL DEFAULT '',
    driver_guide TINYINT(1) NOT NULL DEFAULT 0,
    daily_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
    bio_de TEXT NOT NULL,
    bio_en TEXT NOT NULL,
    emergency_name VARCHAR(150) NOT NULL DEFAULT '',
    emergency_phone VARCHAR(80) NOT NULL DEFAULT '',
    photo_path VARCHAR(255) NULL,
    license_document_path VARCHAR(255) NULL,
    identity_document_path VARCHAR(255) NULL,
    insurance_document_path VARCHAR(255) NULL,
    admin_notes TEXT NOT NULL,
    consent_at DATETIME NULL,
    active TINYINT(1) NOT NULL DEFAULT 0,
    featured TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_guides_status_active (status, active, sort_order),
    INDEX idx_guides_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_templates (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(160) NOT NULL UNIQUE,
    category VARCHAR(40) NOT NULL DEFAULT 'discovery',
    title_de VARCHAR(190) NOT NULL,
    title_en VARCHAR(190) NOT NULL,
    eyebrow_de VARCHAR(190) NOT NULL DEFAULT '',
    eyebrow_en VARCHAR(190) NOT NULL DEFAULT '',
    intro_de TEXT NOT NULL,
    intro_en TEXT NOT NULL,
    description_de MEDIUMTEXT NOT NULL,
    description_en MEDIUMTEXT NOT NULL,
    duration_nights SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    min_travelers TINYINT UNSIGNED NOT NULL DEFAULT 1,
    max_travelers TINYINT UNSIGNED NOT NULL DEFAULT 20,
    price_from DECIMAL(10,2) NOT NULL DEFAULT 0,
    season_de VARCHAR(190) NOT NULL DEFAULT '',
    season_en VARCHAR(190) NOT NULL DEFAULT '',
    difficulty_de VARCHAR(120) NOT NULL DEFAULT '',
    difficulty_en VARCHAR(120) NOT NULL DEFAULT '',
    includes_de TEXT NOT NULL,
    includes_en TEXT NOT NULL,
    excludes_de TEXT NOT NULL,
    excludes_en TEXT NOT NULL,
    image_path VARCHAR(255) NULL,
    featured TINYINT(1) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_tour_templates_public (active, featured, sort_order),
    INDEX idx_tour_templates_category (category, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_template_stops (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tour_template_id INT UNSIGNED NOT NULL,
    destination_id INT UNSIGNED NOT NULL,
    day_start SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    day_end SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    nights TINYINT UNSIGNED NOT NULL DEFAULT 1,
    title_de VARCHAR(190) NOT NULL DEFAULT '',
    title_en VARCHAR(190) NOT NULL DEFAULT '',
    description_de TEXT NOT NULL,
    description_en TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_template_stop_tour FOREIGN KEY (tour_template_id) REFERENCES tour_templates(id) ON DELETE CASCADE,
    CONSTRAINT fk_template_stop_destination FOREIGN KEY (destination_id) REFERENCES destinations(id) ON DELETE RESTRICT,
    INDEX idx_template_stops_route (tour_template_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_template_stop_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tour_template_stop_id INT UNSIGNED NOT NULL,
    catalog_item_id INT UNSIGNED NOT NULL,
    included TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_template_item_stop FOREIGN KEY (tour_template_stop_id) REFERENCES tour_template_stops(id) ON DELETE CASCADE,
    CONSTRAINT fk_template_item_catalog FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE,
    UNIQUE KEY uq_template_stop_item (tour_template_stop_id, catalog_item_id),
    INDEX idx_template_stop_items (tour_template_stop_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_template_prices (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tour_template_id INT UNSIGNED NOT NULL,
    label_de VARCHAR(160) NOT NULL DEFAULT '',
    label_en VARCHAR(160) NOT NULL DEFAULT '',
    valid_from DATE NULL,
    valid_to DATE NULL,
    min_travelers TINYINT UNSIGNED NOT NULL DEFAULT 1,
    max_travelers TINYINT UNSIGNED NOT NULL DEFAULT 20,
    price_per_person DECIMAL(10,2) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_template_price_tour FOREIGN KEY (tour_template_id) REFERENCES tour_templates(id) ON DELETE CASCADE,
    INDEX idx_template_prices (tour_template_id, active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS b2b_agents (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_code VARCHAR(40) NOT NULL UNIQUE,
    company_name VARCHAR(190) NOT NULL,
    contact_name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(80) NOT NULL DEFAULT '',
    address TEXT NOT NULL,
    country VARCHAR(120) NOT NULL DEFAULT '',
    tax_id VARCHAR(120) NOT NULL DEFAULT '',
    commission_percent DECIMAL(5,2) NOT NULL DEFAULT 10.00,
    notes TEXT NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_b2b_agents_active_company (active, company_name),
    INDEX idx_b2b_agents_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portal_users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_type ENUM('customer','agent') NOT NULL DEFAULT 'customer',
    b2b_agent_id INT UNSIGNED NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(80) NOT NULL DEFAULT '',
    language ENUM('de','en') NOT NULL DEFAULT 'de',
    active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_portal_user_agent FOREIGN KEY (b2b_agent_id) REFERENCES b2b_agents(id) ON DELETE SET NULL,
    INDEX idx_portal_users_type_active (user_type, active),
    INDEX idx_portal_users_agent (b2b_agent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reference VARCHAR(24) NOT NULL UNIQUE,
    customer_user_id INT UNSIGNED NULL,
    b2b_agent_id INT UNSIGNED NULL,
    customer_name VARCHAR(150) NOT NULL,
    customer_email VARCHAR(190) NOT NULL,
    customer_phone VARCHAR(80) NOT NULL DEFAULT '',
    language ENUM('de','en') NOT NULL DEFAULT 'de',
    request_type ENUM('tour','beach','ayurveda','maldives') NOT NULL DEFAULT 'tour',
    source_tour_template_id INT UNSIGNED NULL,
    travelers TINYINT UNSIGNED NOT NULL DEFAULT 2,
    adults TINYINT UNSIGNED NOT NULL DEFAULT 2,
    children TINYINT UNSIGNED NOT NULL DEFAULT 0,
    rooms TINYINT UNSIGNED NOT NULL DEFAULT 0,
    hotel_name_de VARCHAR(190) NOT NULL DEFAULT '',
    hotel_name_en VARCHAR(190) NOT NULL DEFAULT '',
    room_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    extra_bed_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    meal_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    services_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    price_markup_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    price_markup_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    vehicle_id INT UNSIGNED NULL,
    vehicle_name_de VARCHAR(120) NOT NULL DEFAULT '',
    vehicle_name_en VARCHAR(120) NOT NULL DEFAULT '',
    vehicle_capacity SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    vehicle_service_type VARCHAR(30) NOT NULL DEFAULT 'with_driver',
    vehicle_days SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    vehicle_daily_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
    vehicle_km_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
    vehicle_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    vehicle_image_path VARCHAR(255) NULL,
    guide_id INT UNSIGNED NULL,
    guide_name VARCHAR(190) NOT NULL DEFAULT '',
    guide_photo_path VARCHAR(255) NULL,
    guide_languages VARCHAR(500) NOT NULL DEFAULT '',
    guide_days SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    guide_daily_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
    guide_cost DECIMAL(10,2) NOT NULL DEFAULT 0,
    start_date DATE NULL,
    duration SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    travel_style VARCHAR(80) NOT NULL DEFAULT '',
    notes TEXT NOT NULL,
    estimate DECIMAL(10,2) NOT NULL DEFAULT 0,
    route_distance_km DECIMAL(10,1) NOT NULL DEFAULT 0,
    route_duration_minutes INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('new','contacted','quoted','confirmed','cancelled','archived') NOT NULL DEFAULT 'new',
    admin_created TINYINT(1) NOT NULL DEFAULT 0,
    created_by_admin_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_customer_user FOREIGN KEY (customer_user_id) REFERENCES portal_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_b2b_agent FOREIGN KEY (b2b_agent_id) REFERENCES b2b_agents(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_guide FOREIGN KEY (guide_id) REFERENCES guides(id) ON DELETE SET NULL,
    INDEX idx_requests_status_created (status, created_at),
    INDEX idx_request_source_template (source_tour_template_id),
    INDEX idx_requests_email (customer_email),
    INDEX idx_requests_customer (customer_user_id, created_at),
    INDEX idx_requests_agent (b2b_agent_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_request_destinations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id INT UNSIGNED NOT NULL,
    destination_id INT UNSIGNED NOT NULL,
    nights TINYINT UNSIGNED NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_request_destination_request FOREIGN KEY (request_id) REFERENCES tour_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_request_destination_destination FOREIGN KEY (destination_id) REFERENCES destinations(id) ON DELETE RESTRICT,
    INDEX idx_request_destination_route (request_id, sort_order),
    INDEX idx_request_destination_place (destination_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tour_request_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id INT UNSIGNED NOT NULL,
    request_destination_id INT UNSIGNED NULL,
    item_id INT UNSIGNED NOT NULL,
    quantity SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    room_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    unit_price DECIMAL(10,2) NOT NULL DEFAULT 0,
    price_basis VARCHAR(30) NOT NULL DEFAULT 'per_person',
    line_total DECIMAL(10,2) NOT NULL DEFAULT 0,
    adult_quantity TINYINT UNSIGNED NOT NULL DEFAULT 0,
    child_quantity TINYINT UNSIGNED NOT NULL DEFAULT 0,
    extra_bed_adults TINYINT UNSIGNED NOT NULL DEFAULT 0,
    extra_bed_children TINYINT UNSIGNED NOT NULL DEFAULT 0,
    extra_bed_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    child_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    meal_plan_code VARCHAR(40) NOT NULL DEFAULT '',
    meal_plan_name_de VARCHAR(120) NOT NULL DEFAULT '',
    meal_plan_name_en VARCHAR(120) NOT NULL DEFAULT '',
    meal_plan_supplement DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_request_item_request FOREIGN KEY (request_id) REFERENCES tour_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_request_item_stop FOREIGN KEY (request_destination_id) REFERENCES tour_request_destinations(id) ON DELETE CASCADE,
    CONSTRAINT fk_request_item_catalog FOREIGN KEY (item_id) REFERENCES catalog_items(id) ON DELETE RESTRICT,
    INDEX idx_request_item_request (request_id),
    INDEX idx_request_item_stop (request_destination_id),
    INDEX idx_request_item_catalog (item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bookings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    booking_reference VARCHAR(24) NOT NULL UNIQUE,
    request_id INT UNSIGNED NOT NULL UNIQUE,
    customer_user_id INT UNSIGNED NULL,
    b2b_agent_id INT UNSIGNED NULL,
    status ENUM('provisional','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'provisional',
    payment_status ENUM('unpaid','partial','paid','refunded') NOT NULL DEFAULT 'unpaid',
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    deposit_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    paid_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    currency CHAR(3) NOT NULL DEFAULT 'EUR',
    travel_start_date DATE NULL,
    travel_end_date DATE NULL,
    payment_due_date DATE NULL,
    agent_commission_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    agent_commission_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    customer_notes TEXT NOT NULL,
    internal_notes TEXT NOT NULL,
    created_by_admin_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_request FOREIGN KEY (request_id) REFERENCES tour_requests(id) ON DELETE RESTRICT,
    CONSTRAINT fk_booking_customer FOREIGN KEY (customer_user_id) REFERENCES portal_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_booking_agent FOREIGN KEY (b2b_agent_id) REFERENCES b2b_agents(id) ON DELETE SET NULL,
    CONSTRAINT fk_booking_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
    INDEX idx_bookings_status_created (status, created_at),
    INDEX idx_bookings_payment_status (payment_status, created_at),
    INDEX idx_bookings_customer (customer_user_id, created_at),
    INDEX idx_bookings_agent (b2b_agent_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS booking_payments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    booking_id INT UNSIGNED NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_date DATE NOT NULL,
    payment_method ENUM('bank_transfer','card','paypal','cash','other') NOT NULL DEFAULT 'bank_transfer',
    transaction_reference VARCHAR(190) NOT NULL DEFAULT '',
    notes TEXT NOT NULL,
    created_by_admin_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_users(id) ON DELETE SET NULL,
    INDEX idx_booking_payments_booking_date (booking_id, payment_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
    setting_key VARCHAR(120) PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration VARCHAR(190) PRIMARY KEY,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
