<?php
declare(strict_types=1);

/**
 * Editable Sri Lanka destination catalogue.
 * Row order: slug, code, names DE/EN, regions DE/EN, intros DE/EN,
 * default nights, price from, accent, latitude, longitude, place ID,
 * sort order, active.
 */
return [
    ['colombo','CMB','Colombo','Colombo','Westprovinz','Western Province','Lebendige Hafenmetropole mit Kolonialarchitektur, Märkten, Tempeln, moderner Gastronomie und Galle Face Green.','A lively port city with colonial architecture, markets, temples, contemporary dining and Galle Face Green.',1,150,'ocean',6.9270790,79.8612440,'',5,1],
    ['negombo','NEG','Negombo','Negombo','Westküste','West Coast','Sanfte Ankunft am Meer, Lagunenleben und kurzer Weg zum Flughafen.','A gentle seaside arrival, lagoon life and easy airport access.',1,110,'sand',7.2083000,79.8358000,'',10,1],
    ['kalpitiya-puttalam','KAL','Kalpitiya & Puttalam','Kalpitiya & Puttalam','Nordwestküste','North-West Coast','Lagunen, Delfine, Kitesurfen und ruhige Küstenlandschaften auf der Kalpitiya-Halbinsel.','Lagoons, dolphins, kitesurfing and quiet coastal landscapes on the Kalpitiya peninsula.',3,170,'ocean',8.2295000,79.7593000,'',12,1],
    ['anuradhapura','ANU','Anuradhapura','Anuradhapura','Nord-Zentralprovinz','North Central Province','Heilige Königsstadt mit großen Stupas, Klosteranlagen und dem verehrten Sri-Maha-Bodhi-Baum.','A sacred royal city of monumental stupas, monasteries and the revered Sri Maha Bodhi tree.',2,160,'ochre',8.3114000,80.4037000,'',15,1],
    ['wilpattu','WIL','Wilpattu','Wilpattu','Nordwestliche Wildnis','North-West Wilderness','Weite Trockenwälder, natürliche Seen und stille Safaris im größten Nationalpark Sri Lankas.','Dry-zone forest, natural lakes and uncrowded safaris in Sri Lanka’s largest national park.',2,285,'clay',8.4582000,80.0510000,'',17,1],
    ['sigiriya','SIG','Sigiriya, Dambulla & Habarana','Sigiriya, Dambulla & Habarana','Kulturdreieck','Cultural Triangle','Felsenfestung, Höhlentempel, Elefantensafaris und stille Dörfer zwischen Reisfeldern.','Rock fortress, cave temples, elephant safaris and quiet villages between rice fields.',3,185,'ochre',7.9570000,80.7603000,'',20,1],
    ['polonnaruwa','POL','Polonnaruwa','Polonnaruwa','Kulturdreieck','Cultural Triangle','Ruinen einer mittelalterlichen Königsstadt, monumentale Buddhas und alte Bewässerungskunst.','Ruins of a medieval royal capital, monumental Buddhas and ancient irrigation landscapes.',2,165,'ochre',7.9403000,81.0188000,'',25,1],
    ['kandy','KAN','Kandy','Kandy','Zentrales Hochland','Central Highlands','Tempelstadt, botanische Gärten und lebendige Kultur im grünen Herzen der Insel.','Temple city, botanical gardens and living culture in the island’s green heart.',2,160,'leaf',7.2906000,80.6337000,'',30,1],
    ['matale-knuckles','MTL','Matale, Riverston & Knuckles','Matale, Riverston & Knuckles','Zentralprovinz','Central Province','Gewürzgärten, Bergdörfer und aussichtsreiche Wanderungen im Knuckles-Gebirge.','Spice gardens, mountain villages and panoramic hiking in the Knuckles range.',2,175,'leaf',7.4675000,80.6234000,'',32,1],
    ['hatton-adams-peak','HAT','Hatton & Adam’s Peak','Hatton & Adam’s Peak','Teeland','Tea Country','Historische Teeplantagen und Ausgangspunkt für die Pilgerwanderung auf den Adam’s Peak.','Historic tea estates and the gateway to the pilgrimage climb of Adam’s Peak.',2,170,'mist',6.8916000,80.5955000,'',34,1],
    ['nuwara-eliya','NUE','Nuwara Eliya','Nuwara Eliya','Zentrales Bergland','Central Highlands','Kühles Hochlandklima, Teeplantagen, koloniale Häuser und Zugang zu Horton Plains.','Cool highland weather, tea estates, colonial houses and access to Horton Plains.',2,190,'mist',6.9497000,80.7891000,'',36,1],
    ['ella','ELA','Ella & Teeland','Ella & Tea Country','Bergland','Hill Country','Panoramazug, Teeberge, Wasserfälle und Wanderungen in kühler Bergluft.','Scenic railways, tea hills, waterfalls and hikes in cool mountain air.',3,215,'mist',6.8667000,81.0466000,'',40,1],
    ['haputale','HAP','Haputale','Haputale','Südliches Bergland','Southern Highlands','Ruhiger Bergort mit Teegütern, Lipton’s Seat und weitem Blick bis zur Südküste.','A peaceful hill town with tea estates, Lipton’s Seat and far-reaching southern views.',2,155,'mist',6.7657000,80.9513000,'',42,1],
    ['kitulgala','KIT','Kitulgala','Kitulgala','Westliches Bergland','Western Highlands','Regenwald, Wildwasser-Rafting, Canyoning und Abenteuer am Kelani-Fluss.','Rainforest, white-water rafting, canyoning and adventure along the Kelani River.',2,165,'leaf',6.9896000,80.4207000,'',44,1],
    ['udawalawe','UDA','Udawalawe','Udawalawe','Südliche Wildnis','Southern Wilderness','Elefantenbeobachtung, offene Landschaften und familienfreundliche Safaris.','Elephant encounters, open landscapes and family-friendly safari experiences.',2,245,'clay',6.4389000,80.8882000,'',45,1],
    ['yala','YAL','Tissamaharama, Yala & Kataragama','Tissamaharama, Yala & Kataragama','Südosten','South East','Private Safari, Leopardenrevier, historische Seen und die heilige Stadt Kataragama.','Private safari, leopard territory, historic reservoirs and the sacred town of Kataragama.',2,275,'clay',6.3725000,81.5185000,'',50,1],
    ['tangalle-rekawa','TAN','Tangalle & Rekawa','Tangalle & Rekawa','Tiefe Südküste','Deep South Coast','Weite Strände, kleine Buchten, Lagunen und geschützte Nistplätze für Meeresschildkröten.','Long beaches, secluded coves, lagoons and protected sea-turtle nesting shores.',3,210,'sand',6.0243000,80.7941000,'',52,1],
    ['matara-dikwella','MAT','Matara & Dikwella','Matara & Dikwella','Südküste','South Coast','Lokales Stadtleben, Tempel, kleine Buchten und entspannte Strandtage rund um Dikwella.','Local city life, temples, small coves and relaxed beach days around Dikwella.',2,170,'ocean',5.9549000,80.5550000,'',54,1],
    ['weligama-mirissa','MIR','Weligama & Mirissa','Weligama & Mirissa','Südküste','South Coast','Surfen, Walbeobachtung, palmengesäumte Buchten und lebendige Strandrestaurants.','Surfing, whale watching, palm-fringed bays and lively beach restaurants.',3,220,'ocean',5.9483000,80.4716000,'',56,1],
    ['koggala-ahangama','KOG','Koggala & Ahangama','Koggala & Ahangama','Südküste','South Coast','Lagunen, Stelzenfischer, Surfstrände und stilvolle kleine Hotels nahe Galle.','Lagoons, stilt fishermen, surf beaches and stylish small hotels near Galle.',3,210,'ocean',5.9885000,80.3286000,'',58,1],
    ['galle','GAL','Galle & Unawatuna','Galle & Unawatuna','Südküste','South Coast','Koloniales Fort, kleine Ateliers, Strandbuchten und warme Meeresluft.','Colonial fort, small studios, beach coves and warm ocean air.',3,240,'ocean',6.0329000,80.2168000,'',60,1],
    ['hikkaduwa','HIK','Hikkaduwa','Hikkaduwa','Südwestküste','South-West Coast','Korallen, Schnorcheln, Surfen und ein lebendiger Küstenort mit vielen Restaurants.','Coral, snorkelling, surfing and a lively coastal town with plentiful dining.',3,195,'ocean',6.1395000,80.1063000,'',62,1],
    ['bentota-beruwala','BEN','Bentota & Beruwala','Bentota & Beruwala','Südwestküste','South-West Coast','Flusslandschaften, Wassersport, Ayurveda-Hotels und lange goldene Strände.','River scenery, water sports, Ayurveda hotels and long golden beaches.',4,225,'sand',6.4214000,79.9985000,'',64,1],
    ['wadduwa-kalutara','WAD','Wadduwa & Kalutara','Wadduwa & Kalutara','Westküste','West Coast','Ruhige Strandresorts, Ayurveda, Kokospalmen und der markante Kalutara-Bodhiya-Tempel.','Relaxed beach resorts, Ayurveda, coconut palms and the landmark Kalutara Bodhiya.',3,190,'sand',6.5854000,79.9607000,'',66,1],
    ['sinharaja','SIN','Sinharaja','Sinharaja','Südwestlicher Regenwald','South-West Rainforest','Geführte Naturwanderungen durch artenreichen tropischen Tieflandregenwald.','Guided nature walks through biodiverse tropical lowland rainforest.',2,195,'leaf',6.4044000,80.4547000,'',68,1],
    ['gal-oya','GOY','Gal Oya','Gal Oya','Östliche Wildnis','Eastern Wilderness','Bootssafaris, Elefanten, indigene Kultur und abgelegene Natur am Senanayake-Samudraya-See.','Boat safaris, elephants, Indigenous culture and remote nature around Senanayake Samudraya.',2,285,'leaf',7.1810000,81.5300000,'',70,1],
    ['arugam-bay-pottuvil','ARU','Arugam Bay & Pottuvil','Arugam Bay & Pottuvil','Südostküste','South-East Coast','Weltbekannte Surfspots, Lagunen, Kumana-Safaris und entspannte Küstenatmosphäre.','World-class surf breaks, lagoons, Kumana safaris and a relaxed coastal atmosphere.',4,205,'ocean',6.8404000,81.8368000,'',72,1],
    ['batticaloa','BAT','Batticaloa','Batticaloa','Ostprovinz','Eastern Province','Lagunenstadt mit kolonialem Fort, Inseln, Tempeln und vielfältiger tamilischer Küche.','A lagoon city of colonial fortifications, islands, temples and distinctive Tamil cuisine.',2,145,'ocean',7.7170000,81.7000000,'',74,1],
    ['pasikudah-kalkudah','PAS','Pasikudah & Kalkudah','Pasikudah & Kalkudah','Ostküste','East Coast','Flache türkisfarbene Bucht, ruhiges Meer und erholsame Strandresorts.','A shallow turquoise bay, calm sea and restful beach resorts.',4,225,'ocean',7.9290000,81.5614000,'',76,1],
    ['trincomalee-nilaveli','TRI','Trincomalee & Nilaveli','Trincomalee & Nilaveli','Nordostküste','North-East Coast','Naturhafen, Tempel, Pigeon Island, Walbeobachtung und lange helle Sandstrände.','Natural harbour, temples, Pigeon Island, whale watching and long pale beaches.',4,230,'ocean',8.5874000,81.2152000,'',78,1],
    ['jaffna','JAF','Jaffna','Jaffna','Nordprovinz','Northern Province','Tamilische Kultur, lebendige Tempel, besondere Küche und Inseln in der Palkstraße.','Tamil culture, vibrant temples, distinctive cuisine and islands in the Palk Strait.',3,170,'ochre',9.6615000,80.0255000,'',80,1],
    ['mannar','MAN','Mannar','Mannar','Nordwesten','North West','Vogelwelt, Baobabs, Adam’s Bridge und eine abgeschiedene Küste voller Geschichte.','Birdlife, baobabs, Adam’s Bridge and a remote coastline rich in history.',2,155,'sand',8.9810000,79.9044000,'',82,1],

    // Specialist destinations are installed as inactive drafts and can be edited and activated by the administrator.
    ['kegalle-pinnawala','KEG','Kegalle & Pinnawala','Kegalle & Pinnawala','Sabaragamuwa','Sabaragamuwa','Kautschuk- und Gewürzlandschaften, Elefanten und ländliche Stopps zwischen Colombo und Kandy.','Rubber and spice landscapes, elephants and rural stops between Colombo and Kandy.',1,140,'leaf',7.2513000,80.3464000,'',101,0],
    ['kurunegala-yapahuwa','KUR','Kurunegala, Yapahuwa & Dambadeniya','Kurunegala, Yapahuwa & Dambadeniya','Nordwestprovinz','North Western Province','Wenig besuchte Königsstädte, Felsenfestungen und ländliche Kulturlandschaften.','Lesser-visited royal capitals, rock fortresses and rural cultural landscapes.',2,145,'ochre',7.4863000,80.3647000,'',102,0],
    ['chilaw-marawila','CHI','Chilaw & Marawila','Chilaw & Marawila','Nordwestküste','North-West Coast','Fischerdörfer, Wallfahrtsorte, Kokospalmen und entspannte Strandhotels.','Fishing communities, pilgrimage sites, coconut groves and relaxed beach hotels.',2,150,'sand',7.5758000,79.7953000,'',103,0],
    ['ratnapura','RAT','Ratnapura','Ratnapura','Sabaragamuwa','Sabaragamuwa','Stadt der Edelsteine und Tor zu Regenwäldern, Wasserfällen und Adam’s Peak.','The city of gems and a gateway to rainforests, waterfalls and Adam’s Peak.',2,150,'leaf',6.6828000,80.3992000,'',104,0],
    ['belihuloya','BEL','Belihuloya','Belihuloya','Südliches Bergland','Southern Highlands','Flüsse, Bergpfade und Eco-Lodges in einer ruhigen Übergangszone zwischen Hochland und Ebene.','Rivers, mountain trails and eco-lodges in a peaceful transition between hills and plains.',2,165,'mist',6.7183000,80.7745000,'',105,0],
    ['mahiyanganaya-wasgamuwa','MAH','Mahiyanganaya & Wasgamuwa','Mahiyanganaya & Wasgamuwa','Uva & Zentralprovinz','Uva & Central Provinces','Alte Pilgerstätten, Vedda-Kultur, Flusslandschaften und abgelegene Elefantensafaris.','Ancient pilgrimage sites, Vedda culture, river landscapes and remote elephant safaris.',2,210,'leaf',7.3327000,81.0004000,'',106,0],
    ['badulla','BAD','Badulla','Badulla','Uva-Provinz','Uva Province','Regionale Marktstadt mit Tempeln, Wasserfällen und authentischem Hochlandalltag.','A regional market town with temples, waterfalls and authentic highland life.',1,135,'mist',6.9934000,81.0550000,'',107,0],
    ['hambantota-bundala','HAM','Hambantota & Bundala','Hambantota & Bundala','Tiefe Südküste','Deep South','Salinen, Lagunen, große Vogelschwärme und Safaris im Bundala-Nationalpark.','Salt pans, lagoons, large bird flocks and safari experiences in Bundala National Park.',2,190,'clay',6.1429000,81.1212000,'',108,0],
    ['mullaitivu','MUL','Mullaitivu','Mullaitivu','Nordostküste','North-East Coast','Abgelegene Strände, Lagunen und wenig besuchte Landschaften im Norden.','Remote beaches, lagoons and little-visited landscapes in the north.',2,135,'ocean',9.2671000,80.8142000,'',109,0],
    ['kilinochchi','KIL','Kilinochchi','Kilinochchi','Nordprovinz','Northern Province','Nördliche Regionalstadt und Ausgangspunkt für Geschichte, Landwirtschaft und Lagunenlandschaften.','A northern regional town and base for history, agriculture and lagoon landscapes.',1,120,'sand',9.3803000,80.3770000,'',110,0],
    ['vavuniya','VAV','Vavuniya','Vavuniya','Nordprovinz','Northern Province','Verkehrsknoten und Tor zwischen dem Kulturdreieck und der Halbinsel Jaffna.','A transport hub and gateway between the Cultural Triangle and Jaffna peninsula.',1,115,'sand',8.7514000,80.4971000,'',111,0],
    ['ampara','AMP','Ampara','Ampara','Ostprovinz','Eastern Province','Reisfelder, Stauseen, Tempel und wenig bekannte Natur- und Kulturorte im Osten.','Rice fields, reservoirs, temples and little-known natural and cultural sites in the east.',2,140,'leaf',7.2975000,81.6820000,'',112,0],
];
