<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require_admin();
$id=max(0,(int)($_GET['id']??0));
$defaults=['agency_code'=>'','company_name'=>'','contact_name'=>'','email'=>'','phone'=>'','address'=>'','country'=>'','tax_id'=>'','commission_percent'=>'10','notes'=>'','active'=>1];
$agent=$defaults;$portalUser=null;
if($id){$stmt=db()->prepare('SELECT * FROM b2b_agents WHERE id=?');$stmt->execute([$id]);$agent=$stmt->fetch();if(!$agent){http_response_code(404);exit('Agent not found');}$u=db()->prepare("SELECT * FROM portal_users WHERE b2b_agent_id=? AND user_type='agent' LIMIT 1");$u->execute([$id]);$portalUser=$u->fetch()?:null;}
if(request_is_post()){
    verify_csrf();foreach(array_keys($defaults) as $key){if($key==='active')continue;$agent[$key]=trim((string)($_POST[$key]??''));}$agent['active']=isset($_POST['active'])?1:0;$agent['agency_code']=strtoupper(preg_replace('/[^A-Za-z0-9_-]/','',$agent['agency_code'])??'');$agent['email']=strtolower($agent['email']);$password=(string)($_POST['portal_password']??'');$errors=[];
    if($agent['agency_code']===''||strlen($agent['agency_code'])>40)$errors[]='Bitte einen eindeutigen Agenturcode eingeben.';if($agent['company_name']===''||$agent['contact_name']==='')$errors[]='Firma und Kontaktperson sind erforderlich.';if(!filter_var($agent['email'],FILTER_VALIDATE_EMAIL))$errors[]='Bitte eine gültige E-Mail-Adresse eingeben.';$commission=str_replace(',','.',$agent['commission_percent']);if(!is_numeric($commission)||(float)$commission<0||(float)$commission>100)$errors[]='Die Provision muss zwischen 0 und 100 Prozent liegen.';$agent['commission_percent']=number_format((float)$commission,2,'.','');
    if(!$portalUser&&strlen($password)<8)$errors[]='Für einen neuen Portalzugang ist ein Passwort mit mindestens 8 Zeichen erforderlich.';if($password!==''&&strlen($password)<8)$errors[]='Das Passwort muss mindestens 8 Zeichen enthalten.';
    $unique=db()->prepare('SELECT COUNT(*) FROM b2b_agents WHERE agency_code=? AND id<>?');$unique->execute([$agent['agency_code'],$id]);if((int)$unique->fetchColumn()>0)$errors[]='Dieser Agenturcode ist bereits vergeben.';$emailCheck=db()->prepare('SELECT COUNT(*) FROM portal_users WHERE email=? AND id<>?');$emailCheck->execute([$agent['email'],(int)($portalUser['id']??0)]);if((int)$emailCheck->fetchColumn()>0)$errors[]='Diese E-Mail-Adresse wird bereits von einem anderen Portalzugang verwendet.';
    if($errors){flash('error',implode(' ',$errors));}else{$pdo=db();try{$pdo->beginTransaction();if($id){$save=$pdo->prepare('UPDATE b2b_agents SET agency_code=?,company_name=?,contact_name=?,email=?,phone=?,address=?,country=?,tax_id=?,commission_percent=?,notes=?,active=? WHERE id=?');$save->execute([$agent['agency_code'],$agent['company_name'],$agent['contact_name'],$agent['email'],substr($agent['phone'],0,80),$agent['address'],$agent['country'],$agent['tax_id'],$agent['commission_percent'],$agent['notes'],$agent['active'],$id]);}else{$save=$pdo->prepare('INSERT INTO b2b_agents (agency_code,company_name,contact_name,email,phone,address,country,tax_id,commission_percent,notes,active) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$save->execute([$agent['agency_code'],$agent['company_name'],$agent['contact_name'],$agent['email'],substr($agent['phone'],0,80),$agent['address'],$agent['country'],$agent['tax_id'],$agent['commission_percent'],$agent['notes'],$agent['active']]);$id=(int)$pdo->lastInsertId();}
        if($portalUser){if($password!=='')$pdo->prepare("UPDATE portal_users SET name=?,email=?,phone=?,active=?,password_hash=? WHERE id=?")->execute([$agent['contact_name'],$agent['email'],substr($agent['phone'],0,80),$agent['active'],password_hash($password,PASSWORD_DEFAULT),(int)$portalUser['id']]);else $pdo->prepare('UPDATE portal_users SET name=?,email=?,phone=?,active=? WHERE id=?')->execute([$agent['contact_name'],$agent['email'],substr($agent['phone'],0,80),$agent['active'],(int)$portalUser['id']]);}else{$pdo->prepare("INSERT INTO portal_users (user_type,b2b_agent_id,name,email,password_hash,phone,language,active) VALUES ('agent',?,?,?,?,?,'de',?)")->execute([$id,$agent['contact_name'],$agent['email'],password_hash($password,PASSWORD_DEFAULT),substr($agent['phone'],0,80),$agent['active']]);}
        $pdo->commit();flash('success','B2B-Agentur und Portalzugang wurden gespeichert.');redirect('admin/agent-edit.php?id='.$id);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Speichern fehlgeschlagen: '.$e->getMessage());}}
}
$adminPage='agents';$adminTitle=$id?'Agentur bearbeiten':'Neue Agentur';require __DIR__.'/_header.php';
?>
<div class="admin-content narrow"><a class="back-admin" href="agents.php">← B2B-Agenturen</a><div class="page-heading compact"><div><p>PARTNERVERTRIEB</p><h1><?= $id?'Agentur bearbeiten':'Neue B2B-Agentur' ?></h1><span>Firmendaten, Provision und sicheren Portalzugang pflegen.</span></div></div><form class="editor-form" method="post"><?= csrf_field() ?>
<section class="admin-card form-card"><div class="card-head"><div><h2>Agenturdaten</h2><p>Interne Zuordnung und Geschäftskontakt</p></div></div><div class="form-grid"><label>Agenturcode<input name="agency_code" required maxlength="40" value="<?= e($agent['agency_code']) ?>" placeholder="DE-001"></label><label>Firmenname<input name="company_name" required maxlength="190" value="<?= e($agent['company_name']) ?>"></label><label>Kontaktperson<input name="contact_name" required maxlength="150" value="<?= e($agent['contact_name']) ?>"></label><label>E-Mail / Portal-Login<input name="email" type="email" required maxlength="190" value="<?= e($agent['email']) ?>"></label><label>Telefon<input name="phone" maxlength="80" value="<?= e($agent['phone']) ?>"></label><label>Land<input name="country" maxlength="120" value="<?= e($agent['country']) ?>"></label><label>Steuer-/Registriernummer<input name="tax_id" maxlength="120" value="<?= e($agent['tax_id']) ?>"></label><label>Provision (%)<input name="commission_percent" type="number" min="0" max="100" step="0.01" required value="<?= e($agent['commission_percent']) ?>"><small>Wird bei jeder neuen Buchung als Snapshot gespeichert.</small></label><label class="span-two">Adresse<textarea name="address" rows="3"><?= e($agent['address']) ?></textarea></label><label class="span-two">Interne Notizen<textarea name="notes" rows="4"><?= e($agent['notes']) ?></textarea></label><label class="check"><input type="checkbox" name="active" value="1"<?= $agent['active']?' checked':'' ?>> Aktiv und Portalzugang freigeben</label></div></section>
<section class="admin-card form-card"><div class="card-head"><div><h2>Portalzugang</h2><p><?= $portalUser?'Passwort nur ausfüllen, wenn es geändert werden soll.':'Für den ersten Login ist ein Passwort erforderlich.' ?></p></div></div><div class="form-grid"><label>Neues Passwort<input name="portal_password" type="password" minlength="8" autocomplete="new-password"<?= $portalUser?'':' required' ?>><small>Mindestens 8 Zeichen. Das Passwort wird gehasht gespeichert.</small></label><?php if($portalUser):?><div class="admin-account-meta"><strong>Letzter Login</strong><span><?= $portalUser['last_login_at']?e(date('d.m.Y H:i',strtotime($portalUser['last_login_at']))):'Noch nie' ?></span></div><?php endif;?></div></section>
<div class="form-actions"><a href="agents.php">Abbrechen</a><button class="primary-button" type="submit">Agentur speichern</button></div></form></div>
<?php require __DIR__.'/_footer.php';?>
