<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';require_admin();
require_admin_permission('bookings');
$status=in_array($_GET['status']??'', ['provisional','confirmed','in_progress','completed','cancelled'],true)?(string)$_GET['status']:'';$query=trim((string)($_GET['q']??''));
$sql='SELECT b.*,r.reference,r.customer_name,r.customer_email,r.request_type,r.travelers,r.duration,a.company_name FROM bookings b JOIN tour_requests r ON r.id=b.request_id LEFT JOIN b2b_agents a ON a.id=b.b2b_agent_id WHERE 1=1';$params=[];if($status!==''){$sql.=' AND b.status=?';$params[]=$status;}if($query!==''){$sql.=' AND (b.booking_reference LIKE ? OR r.reference LIKE ? OR r.customer_name LIKE ? OR r.customer_email LIKE ? OR a.company_name LIKE ?)';$like='%'.$query.'%';array_push($params,$like,$like,$like,$like,$like);}$sql.=' ORDER BY b.created_at DESC LIMIT 250';$stmt=db()->prepare($sql);$stmt->execute($params);$bookings=$stmt->fetchAll();$counts=db()->query('SELECT status,COUNT(*) total FROM bookings GROUP BY status')->fetchAll(PDO::FETCH_KEY_PAIR);
$statusLabels=['provisional'=>'Vorläufig','confirmed'=>'Bestätigt','in_progress'=>'Reise läuft','completed'=>'Abgeschlossen','cancelled'=>'Storniert'];$paymentLabels=['unpaid'=>'Offen','partial'=>'Teilbezahlt','paid'=>'Bezahlt','refunded'=>'Erstattet'];
$adminPage='bookings';$adminTitle='Buchungen';require __DIR__.'/_header.php';?>
<div class="admin-content"><div class="page-heading compact"><div><p>BUCHUNGSMANAGEMENT</p><h1>Buchungen</h1><span>Bestätigungen, Reisetermine, Zahlungen und Restbeträge verwalten.</span></div><a class="secondary-button" href="requests.php">Reiseanfrage öffnen</a></div><nav class="filter-tabs"><a class="<?= $status===''?'active':'' ?>" href="bookings.php">Alle <b><?= array_sum(array_map('intval',$counts)) ?></b></a><?php foreach($statusLabels as $value=>$label):?><a class="<?= $status===$value?'active':'' ?>" href="?status=<?= e($value) ?>"><?= e($label) ?> <b><?= (int)($counts[$value]??0) ?></b></a><?php endforeach;?></nav>
<section class="admin-card"><form class="table-toolbar" method="get"><?php if($status):?><input type="hidden" name="status" value="<?= e($status) ?>"><?php endif;?><input name="q" value="<?= e($query) ?>" placeholder="Buchung, Kunde, E-Mail oder Agentur …"><button>Suchen</button><span><?= count($bookings) ?> Ergebnisse</span></form><?php if(!$bookings):?><div class="empty"><span>◇</span><h3>Keine Buchungen gefunden</h3><p>Eine Reiseanfrage kann in der Detailansicht in eine Buchung umgewandelt werden.</p></div><?php else:?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Buchung / Kunde</th><th>Reise</th><th>Agentur</th><th>Gesamt / Offen</th><th>Zahlung</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($bookings as $booking):$balance=max(0,(float)$booking['total_amount']-(float)$booking['paid_amount']);?><tr><td><strong><?= e($booking['booking_reference']) ?> · <?= e($booking['customer_name']) ?></strong><small><?= e($booking['customer_email']) ?> · <?= e(date('d.m.Y',strtotime($booking['created_at']))) ?></small></td><td><?= e(strtoupper($booking['request_type'])) ?><small><?= (int)$booking['travelers'] ?> Pers. · <?= (int)$booking['duration'] ?> Nächte<?= $booking['travel_start_date']?' · '.e(date('d.m.Y',strtotime($booking['travel_start_date']))):'' ?></small></td><td><?= e($booking['company_name']?:'Direktkunde') ?></td><td><strong><?= e(money_precise($booking['total_amount'])) ?></strong><small>Offen: <?= e(money_precise($balance)) ?></small></td><td><span class="status <?= $booking['payment_status']==='paid'?'confirmed':($booking['payment_status']==='partial'?'quoted':'new') ?>"><?= e($paymentLabels[$booking['payment_status']]??$booking['payment_status']) ?></span></td><td><span class="status <?= e($booking['status']==='provisional'?'new':($booking['status']==='confirmed'?'confirmed':'contacted')) ?>"><?= e($statusLabels[$booking['status']]??$booking['status']) ?></span></td><td><a href="booking.php?id=<?= (int)$booking['id'] ?>">Öffnen →</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div>
<?php require __DIR__.'/_footer.php';?>
