<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';require_admin();require_admin_permission('bookings',request_is_post());$id=max(0,(int)($_GET['id']??0));
$loadBooking=static function(int $id):array{$stmt=db()->prepare('SELECT b.*,r.reference,r.request_type,r.customer_name,r.customer_email,r.customer_phone,r.travelers,r.duration,r.hotel_name_de,a.company_name,a.agency_code FROM bookings b JOIN tour_requests r ON r.id=b.request_id LEFT JOIN b2b_agents a ON a.id=b.b2b_agent_id WHERE b.id=?');$stmt->execute([$id]);return $stmt->fetch()?:[];};$booking=$loadBooking($id);if(!$booking){http_response_code(404);exit('Booking not found');}
if(request_is_post()){
 verify_csrf();$action=(string)($_POST['action']??'save');$pdo=db();try{
  if($action==='add_payment'){$amount=round((float)str_replace(',','.',(string)($_POST['amount']??0)),2);$date=(string)($_POST['payment_date']??'');$method=in_array($_POST['payment_method']??'', ['bank_transfer','card','paypal','cash','other'],true)?(string)$_POST['payment_method']:'other';if($amount<=0)throw new RuntimeException('Der Zahlungsbetrag muss größer als 0 sein.');$dateValue=DateTimeImmutable::createFromFormat('Y-m-d',$date);if(!$dateValue||$dateValue->format('Y-m-d')!==$date)throw new RuntimeException('Bitte ein gültiges Zahlungsdatum wählen.');$pdo->prepare('INSERT INTO booking_payments (booking_id,amount,payment_date,payment_method,transaction_reference,notes,created_by_admin_id) VALUES (?,?,?,?,?,?,?)')->execute([$id,$amount,$date,$method,substr(trim((string)($_POST['transaction_reference']??'')),0,190),substr(trim((string)($_POST['payment_notes']??'')),0,2000),(int)admin_user()['id']]);
  }elseif($action==='delete_payment'){$paymentId=max(0,(int)($_POST['payment_id']??0));$pdo->prepare('DELETE FROM booking_payments WHERE id=? AND booking_id=?')->execute([$paymentId,$id]);
  }else{$status=in_array($_POST['status']??'', ['provisional','confirmed','in_progress','completed','cancelled'],true)?(string)$_POST['status']:'provisional';$total=max(0,round((float)str_replace(',','.',(string)($_POST['total_amount']??0)),2));$deposit=max(0,round((float)str_replace(',','.',(string)($_POST['deposit_amount']??0)),2));$commission=max(0,min(100,(float)str_replace(',','.',(string)($_POST['agent_commission_percent']??0))));$start=trim((string)($_POST['travel_start_date']??''))?:null;$end=trim((string)($_POST['travel_end_date']??''))?:null;$due=trim((string)($_POST['payment_due_date']??''))?:null;$pdo->prepare('UPDATE bookings SET status=?,total_amount=?,deposit_amount=?,travel_start_date=?,travel_end_date=?,payment_due_date=?,agent_commission_percent=?,agent_commission_amount=?,customer_notes=?,internal_notes=? WHERE id=?')->execute([$status,$total,$deposit,$start,$end,$due,$commission,round($total*$commission/100,2),substr(trim((string)($_POST['customer_notes']??'')),0,4000),substr(trim((string)($_POST['internal_notes']??'')),0,4000),$id]);$pdo->prepare('UPDATE tour_requests SET status=? WHERE id=?')->execute([$status==='cancelled'?'cancelled':'confirmed',(int)$booking['request_id']]);}
  $paidStmt=$pdo->prepare('SELECT COALESCE(SUM(amount),0) FROM booking_payments WHERE booking_id=?');$paidStmt->execute([$id]);$paid=round((float)$paidStmt->fetchColumn(),2);$fresh=$loadBooking($id);$paymentStatus=$paid<=0?'unpaid':($paid+0.005>=(float)$fresh['total_amount']?'paid':'partial');$pdo->prepare('UPDATE bookings SET paid_amount=?,payment_status=? WHERE id=?')->execute([$paid,$paymentStatus,$id]);flash('success',$action==='save'?'Buchung wurde gespeichert.':'Zahlungsverlauf wurde aktualisiert.');
 }catch(Throwable $e){flash('error','Speichern fehlgeschlagen: '.$e->getMessage());}redirect('admin/booking.php?id='.$id);
}
$booking=$loadBooking($id);$payStmt=db()->prepare('SELECT p.*,a.name AS admin_name FROM booking_payments p LEFT JOIN admin_users a ON a.id=p.created_by_admin_id WHERE p.booking_id=? ORDER BY p.payment_date DESC,p.id DESC');$payStmt->execute([$id]);$payments=$payStmt->fetchAll();$balance=max(0,(float)$booking['total_amount']-(float)$booking['paid_amount']);
$statusLabels=['provisional'=>'Vorläufig','confirmed'=>'Bestätigt','in_progress'=>'Reise läuft','completed'=>'Abgeschlossen','cancelled'=>'Storniert'];$paymentLabels=['unpaid'=>'Offen','partial'=>'Teilbezahlt','paid'=>'Bezahlt','refunded'=>'Erstattet'];$methodLabels=['bank_transfer'=>'Überweisung','card'=>'Karte','paypal'=>'PayPal','cash'=>'Bar','other'=>'Sonstige'];$isHotel=in_array($booking['request_type'],['beach','ayurveda','maldives'],true);
$adminPage='bookings';$adminTitle='Buchung '.$booking['booking_reference'];require __DIR__.'/_header.php';?>
<div class="admin-content"><a class="back-admin" href="bookings.php">← Alle Buchungen</a><div class="page-heading request-heading"><div><p><?= e($booking['booking_reference']) ?> · Anfrage <?= e($booking['reference']) ?></p><h1><?= e($booking['customer_name']) ?></h1><span><?= e($booking['company_name']?'B2B · '.$booking['company_name']:'Direktkunde') ?></span></div><div class="request-actions"><a class="secondary-button" href="request.php?id=<?= (int)$booking['request_id'] ?>">Anfrage öffnen</a><a class="primary-button" target="_blank" href="<?= e(url(($isHotel?'stay-proposal.php':'itinerary.php').'?ref='.urlencode($booking['reference']))) ?>">⌁ Dokument drucken</a></div></div>
<section class="booking-admin-stats"><article><small>Gesamt</small><strong><?= e(money_precise($booking['total_amount'])) ?></strong></article><article><small>Bezahlt</small><strong><?= e(money_precise($booking['paid_amount'])) ?></strong></article><article><small>Offen</small><strong><?= e(money_precise($balance)) ?></strong></article><article><small>Zahlungsstatus</small><strong><?= e($paymentLabels[$booking['payment_status']]??$booking['payment_status']) ?></strong></article></section>
<div class="detail-grid"><div><form class="editor-form" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save"><section class="admin-card form-card"><div class="card-head"><div><h2>Buchung bearbeiten</h2><p>Status, Preise, Reisetermine und Hinweise</p></div></div><div class="form-grid thirds"><label>Status<select name="status"><?php foreach($statusLabels as $value=>$label):?><option value="<?= e($value) ?>"<?= selected($value,$booking['status']) ?>><?= e($label) ?></option><?php endforeach;?></select></label><label>Gesamtbetrag (€)<input name="total_amount" type="number" min="0" step="0.01" required value="<?= e($booking['total_amount']) ?>"></label><label>Vereinbarte Anzahlung (€)<input name="deposit_amount" type="number" min="0" step="0.01" value="<?= e($booking['deposit_amount']) ?>"></label><label>Reisebeginn<input name="travel_start_date" type="date" value="<?= e($booking['travel_start_date']) ?>"></label><label>Reiseende<input name="travel_end_date" type="date" value="<?= e($booking['travel_end_date']) ?>"></label><label>Zahlungsziel<input name="payment_due_date" type="date" value="<?= e($booking['payment_due_date']) ?>"></label><label>Agenturprovision (%)<input name="agent_commission_percent" type="number" min="0" max="100" step="0.01" value="<?= e($booking['agent_commission_percent']) ?>"<?= $booking['b2b_agent_id']?'':' readonly' ?>></label><label class="span-two">Hinweis für Kunde / Agentur<textarea name="customer_notes" rows="4"><?= e($booking['customer_notes']) ?></textarea></label><label class="span-two">Interne Notizen<textarea name="internal_notes" rows="4"><?= e($booking['internal_notes']) ?></textarea></label></div></section><div class="form-actions"><button class="primary-button" type="submit">Buchung speichern</button></div></form>
<section class="admin-card booking-payment-card"><div class="card-head"><div><h2>Zahlungsverlauf</h2><p>Einzahlungen und Referenzen</p></div></div><?php if(!$payments):?><div class="empty small">Noch keine Zahlung erfasst.</div><?php else:?><div class="admin-payment-list"><?php foreach($payments as $payment):?><article><div><strong><?= e($methodLabels[$payment['payment_method']]??$payment['payment_method']) ?> · <?= e(date('d.m.Y',strtotime($payment['payment_date']))) ?></strong><small><?= e($payment['transaction_reference']?:'ohne Referenz') ?><?= $payment['notes']?' · '.e($payment['notes']):'' ?></small></div><b><?= e(money_precise($payment['amount'])) ?></b><form method="post" onsubmit="return confirm('Zahlung wirklich entfernen?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete_payment"><input type="hidden" name="payment_id" value="<?= (int)$payment['id'] ?>"><button type="submit">Entfernen</button></form></article><?php endforeach;?></div><?php endif;?></section></div>
<aside class="detail-side"><section class="admin-card info-card"><h2>Kunde</h2><dl><dt>Name</dt><dd><?= e($booking['customer_name']) ?></dd><dt>E-Mail</dt><dd><a href="mailto:<?= e($booking['customer_email']) ?>"><?= e($booking['customer_email']) ?></a></dd><dt>Telefon</dt><dd><?= e($booking['customer_phone']?:'—') ?></dd><dt>Reisende</dt><dd><?= (int)$booking['travelers'] ?></dd><dt>Nächte</dt><dd><?= (int)$booking['duration'] ?></dd></dl></section><?php if($booking['b2b_agent_id']):?><section class="admin-card info-card"><h2>B2B-Agentur</h2><dl><dt>Firma</dt><dd><?= e($booking['company_name']) ?></dd><dt>Code</dt><dd><?= e($booking['agency_code']) ?></dd><dt>Provision</dt><dd><?= e(number_format((float)$booking['agent_commission_percent'],2,',','.')) ?> % · <?= e(money_precise($booking['agent_commission_amount'])) ?></dd></dl></section><?php endif;?><section class="admin-card form-card"><div class="card-head"><div><h2>Zahlung erfassen</h2><p>Wird sofort zum Saldo gerechnet.</p></div></div><form class="payment-entry-form" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="add_payment"><label>Betrag (€)<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Zahlungsdatum<input name="payment_date" type="date" required value="<?= e(date('Y-m-d')) ?>"></label><label>Zahlungsart<select name="payment_method"><?php foreach($methodLabels as $value=>$label):?><option value="<?= e($value) ?>"><?= e($label) ?></option><?php endforeach;?></select></label><label>Transaktionsreferenz<input name="transaction_reference" maxlength="190"></label><label>Notiz<textarea name="payment_notes" rows="3"></textarea></label><button class="primary-button" type="submit">Zahlung speichern</button></form></section></aside></div></div>
<?php require __DIR__.'/_footer.php';?>
