<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';require_admin();
$query=trim((string)($_GET['q']??''));$active=($_GET['active']??'')==='0'?'0':(($_GET['active']??'')==='1'?'1':'');
$sql="SELECT u.*,
      (SELECT COUNT(*) FROM tour_requests r WHERE r.customer_user_id=u.id) request_count,
      (SELECT COUNT(*) FROM bookings b WHERE b.customer_user_id=u.id) booking_count,
      (SELECT COALESCE(SUM(b.total_amount),0) FROM bookings b WHERE b.customer_user_id=u.id AND b.status<>'cancelled') booking_value
      FROM portal_users u WHERE u.user_type='customer'";$params=[];if($active!==''){$sql.=' AND u.active=?';$params[]=(int)$active;}if($query!==''){$sql.=' AND (u.name LIKE ? OR u.email LIKE ? OR u.phone LIKE ?)';$like='%'.$query.'%';array_push($params,$like,$like,$like);}$sql.=' ORDER BY u.created_at DESC LIMIT 250';$stmt=db()->prepare($sql);$stmt->execute($params);$customers=$stmt->fetchAll();$counts=db()->query("SELECT active,COUNT(*) total FROM portal_users WHERE user_type='customer' GROUP BY active")->fetchAll(PDO::FETCH_KEY_PAIR);
$adminPage='customers';$adminTitle='Kundenkonten';require __DIR__.'/_header.php';?>
<div class="admin-content"><div class="page-heading compact"><div><p>KUNDENVERWALTUNG</p><h1>Kundenkonten</h1><span>Registrierte Kunden, Anfragen, Buchungen und Portalstatus.</span></div></div><nav class="filter-tabs"><a class="<?= $active===''?'active':'' ?>" href="customers.php">Alle <b><?= array_sum(array_map('intval',$counts)) ?></b></a><a class="<?= $active==='1'?'active':'' ?>" href="?active=1">Aktiv <b><?= (int)($counts[1]??0) ?></b></a><a class="<?= $active==='0'?'active':'' ?>" href="?active=0">Inaktiv <b><?= (int)($counts[0]??0) ?></b></a></nav>
<section class="admin-card"><form class="table-toolbar" method="get"><?php if($active!==''):?><input type="hidden" name="active" value="<?= e($active) ?>"><?php endif;?><input name="q" value="<?= e($query) ?>" placeholder="Name, E-Mail oder Telefon …"><button>Suchen</button><span><?= count($customers) ?> Ergebnisse</span></form><?php if(!$customers):?><div class="empty"><span>◇</span><h3>Noch keine Kundenkonten</h3><p>Registrierungen über die Website erscheinen automatisch hier.</p></div><?php else:?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Kunde</th><th>Registrierung / Login</th><th>Anfragen</th><th>Buchungen</th><th>Buchungswert</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($customers as $customer):?><tr><td><strong><?= e($customer['name']) ?></strong><small><?= e($customer['email']) ?><?= $customer['phone']?' · '.e($customer['phone']):'' ?></small></td><td><?= e(date('d.m.Y',strtotime($customer['created_at']))) ?><small><?= $customer['last_login_at']?'Letzter Login '.e(date('d.m.Y H:i',strtotime($customer['last_login_at']))):'Noch kein Login' ?></small></td><td><?= (int)$customer['request_count'] ?></td><td><?= (int)$customer['booking_count'] ?></td><td><strong><?= e(money_precise($customer['booking_value'])) ?></strong></td><td><span class="status <?= $customer['active']?'confirmed':'archived' ?>"><?= $customer['active']?'Aktiv':'Gesperrt' ?></span></td><td><a href="customer.php?id=<?= (int)$customer['id'] ?>">Öffnen →</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div>
<?php require __DIR__.'/_footer.php';?>
