<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';require_admin();require_admin_permission('customers',request_is_post());$id=max(0,(int)($_GET['id']??0));$stmt=db()->prepare("SELECT * FROM portal_users WHERE id=? AND user_type='customer'");$stmt->execute([$id]);$customer=$stmt->fetch();if(!$customer){http_response_code(404);exit('Customer not found');}
if(request_is_post()){
 verify_csrf();$name=trim((string)($_POST['name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$phone=substr(trim((string)($_POST['phone']??'')),0,80);$language=($_POST['language']??'de')==='en'?'en':'de';$active=isset($_POST['active'])?1:0;$password=(string)($_POST['new_password']??'');$errors=[];if($name===''||strlen($name)>150)$errors[]='Bitte einen Namen eingeben.';if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Bitte eine gültige E-Mail-Adresse eingeben.';if($password!==''&&strlen($password)<8)$errors[]='Das neue Passwort muss mindestens 8 Zeichen enthalten.';$check=db()->prepare('SELECT COUNT(*) FROM portal_users WHERE email=? AND id<>?');$check->execute([$email,$id]);if((int)$check->fetchColumn()>0)$errors[]='Diese E-Mail-Adresse ist bereits vergeben.';
 if($errors)flash('error',implode(' ',$errors));else{if($password!=='')db()->prepare('UPDATE portal_users SET name=?,email=?,phone=?,language=?,active=?,password_hash=? WHERE id=?')->execute([$name,$email,$phone,$language,$active,password_hash($password,PASSWORD_DEFAULT),$id]);else db()->prepare('UPDATE portal_users SET name=?,email=?,phone=?,language=?,active=? WHERE id=?')->execute([$name,$email,$phone,$language,$active,$id]);flash('success','Kundenkonto wurde gespeichert.');redirect('admin/customer.php?id='.$id);}
}
$requestStmt=db()->prepare('SELECT r.*,b.id AS booking_id,b.booking_reference FROM tour_requests r LEFT JOIN bookings b ON b.request_id=r.id WHERE r.customer_user_id=? ORDER BY r.created_at DESC');$requestStmt->execute([$id]);$requests=$requestStmt->fetchAll();$bookingStmt=db()->prepare('SELECT * FROM bookings WHERE customer_user_id=? ORDER BY created_at DESC');$bookingStmt->execute([$id]);$bookings=$bookingStmt->fetchAll();
$adminPage='customers';$adminTitle='Kunde '.$customer['name'];require __DIR__.'/_header.php';?>
<div class="admin-content"><a class="back-admin" href="customers.php">← Kundenkonten</a><div class="page-heading compact"><div><p>KUNDENKONTO · <?= e(date('d.m.Y',strtotime($customer['created_at']))) ?></p><h1><?= e($customer['name']) ?></h1><span><?= e($customer['email']) ?> · <?= count($requests) ?> Anfragen · <?= count($bookings) ?> Buchungen</span></div></div><div class="detail-grid"><div><form class="editor-form" method="post"><?= csrf_field() ?><section class="admin-card form-card"><div class="card-head"><div><h2>Kontodaten</h2><p>Kontakt, Sprache und Portalzugang</p></div></div><div class="form-grid"><label>Name<input name="name" required maxlength="150" value="<?= e($customer['name']) ?>"></label><label>E-Mail<input name="email" type="email" required maxlength="190" value="<?= e($customer['email']) ?>"></label><label>Telefon / WhatsApp<input name="phone" maxlength="80" value="<?= e($customer['phone']) ?>"></label><label>Sprache<select name="language"><option value="de"<?= selected('de',$customer['language']) ?>>Deutsch</option><option value="en"<?= selected('en',$customer['language']) ?>>English</option></select></label><label>Neues Passwort<input name="new_password" type="password" minlength="8" autocomplete="new-password"><small>Leer lassen, um das bisherige Passwort zu behalten.</small></label><label class="check"><input type="checkbox" name="active" value="1"<?= $customer['active']?' checked':'' ?>> Portalzugang aktiv</label></div></section><div class="form-actions"><button class="primary-button" type="submit">Kundenkonto speichern</button></div></form>
<section class="admin-card booking-payment-card"><div class="card-head"><div><h2>Anfragen</h2><p>Mit diesem Kundenkonto verknüpft</p></div></div><?php if(!$requests):?><div class="empty small">Keine Anfragen vorhanden.</div><?php else:?><div class="admin-payment-list"><?php foreach($requests as $request):?><article><div><strong><?= e($request['booking_reference']?:$request['reference']) ?> · <?= e(strtoupper($request['request_type'])) ?></strong><small><?= e(date('d.m.Y',strtotime($request['created_at']))) ?> · <?= (int)$request['duration'] ?> Nächte</small></div><b><?= e(money_precise($request['estimate'])) ?></b><a href="<?= e($request['booking_id']?'booking.php?id='.(int)$request['booking_id']:'request.php?id='.(int)$request['id']) ?>">Öffnen →</a></article><?php endforeach;?></div><?php endif;?></section></div><aside class="detail-side"><section class="admin-card info-card"><h2>Kontoübersicht</h2><dl><dt>Status</dt><dd><?= $customer['active']?'Aktiv':'Gesperrt' ?></dd><dt>Registriert</dt><dd><?= e(date('d.m.Y H:i',strtotime($customer['created_at']))) ?></dd><dt>Letzter Login</dt><dd><?= $customer['last_login_at']?e(date('d.m.Y H:i',strtotime($customer['last_login_at']))):'Noch nie' ?></dd><dt>Anfragen</dt><dd><?= count($requests) ?></dd><dt>Buchungen</dt><dd><?= count($bookings) ?></dd></dl></section></aside></div></div>
<?php require __DIR__.'/_footer.php';?>
