<?php
declare(strict_types=1);
require dirname(__DIR__) . '/includes/bootstrap.php';
require_admin();
$id=max(0,(int)($_GET['id']??$_POST['id']??0));
$guide=['id'=>0,'guide_code'=>'','status'=>'pending','first_name'=>'','last_name'=>'','display_name'=>'','email'=>'','phone'=>'','whatsapp'=>'','date_of_birth'=>'','gender'=>'','nationality'=>'','address'=>'','city'=>'','district'=>'','country'=>'Sri Lanka','nic_passport'=>'','license_number'=>'','license_type'=>'','license_expiry'=>'','tourism_registration'=>'','years_experience'=>0,'languages'=>'','service_regions'=>'','specializations'=>'','driver_guide'=>0,'daily_rate'=>0,'bio_de'=>'','bio_en'=>'','emergency_name'=>'','emergency_phone'=>'','photo_path'=>'','license_document_path'=>'','identity_document_path'=>'','insurance_document_path'=>'','admin_notes'=>'','active'=>0,'featured'=>0,'sort_order'=>100];
if($id){$stmt=db()->prepare('SELECT * FROM guides WHERE id=?');$stmt->execute([$id]);$loaded=$stmt->fetch();if(!$loaded){http_response_code(404);exit('Guide not found');}$guide=$loaded;}
if(request_is_post()){
    verify_csrf();
    try{
        $first=substr(trim((string)($_POST['first_name']??'')),0,100);$last=substr(trim((string)($_POST['last_name']??'')),0,100);$email=strtolower(substr(trim((string)($_POST['email']??'')),0,190));$display=substr(trim((string)($_POST['display_name']??'')),0,190)?:trim($first.' '.$last);$license=substr(trim((string)($_POST['license_number']??'')),0,120);$languages=substr(trim((string)($_POST['languages']??'')),0,500);
        if($first===''||$last===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$display===''||$license===''||$languages==='')throw new RuntimeException('Pflichtfelder fehlen.');
        $code=strtoupper(trim((string)($_POST['guide_code']??'')));$code=trim((string)preg_replace('/[^A-Z0-9-]+/','-',$code),'-');if($code==='')$code='G-'.date('ym').'-'.strtoupper(bin2hex(random_bytes(2)));
        $photo=isset($_POST['remove_photo'])?'':upload_image($_FILES['photo']??[],(string)$guide['photo_path']);
        $licenseDoc=upload_private_guide_document($_FILES['license_document']??[],(string)$guide['license_document_path']);
        $identityDoc=upload_private_guide_document($_FILES['identity_document']??[],(string)$guide['identity_document_path']);
        $insuranceDoc=upload_private_guide_document($_FILES['insurance_document']??[],(string)$guide['insurance_document_path']);
        $status=in_array($_POST['status']??'', ['pending','approved','suspended','rejected'],true)?(string)$_POST['status']:'pending';$active=$status==='approved'&&isset($_POST['active'])?1:0;
        $values=[$code,$status,$first,$last,$display,$email,substr(trim((string)($_POST['phone']??'')),0,80),substr(trim((string)($_POST['whatsapp']??'')),0,80),trim((string)($_POST['date_of_birth']??''))?:null,substr(trim((string)($_POST['gender']??'')),0,40),substr(trim((string)($_POST['nationality']??'')),0,100),substr(trim((string)($_POST['address']??'')),0,2000),substr(trim((string)($_POST['city']??'')),0,120),substr(trim((string)($_POST['district']??'')),0,120),substr(trim((string)($_POST['country']??'')),0,120),substr(trim((string)($_POST['nic_passport']??'')),0,120),$license,substr(trim((string)($_POST['license_type']??'')),0,120),trim((string)($_POST['license_expiry']??''))?:null,substr(trim((string)($_POST['tourism_registration']??'')),0,120),max(0,min(70,(int)($_POST['years_experience']??0))),$languages,substr(trim((string)($_POST['service_regions']??'')),0,500),substr(trim((string)($_POST['specializations']??'')),0,500),isset($_POST['driver_guide'])?1:0,max(0,round((float)str_replace(',','.',(string)($_POST['daily_rate']??0)),2)),substr(trim((string)($_POST['bio_de']??'')),0,5000),substr(trim((string)($_POST['bio_en']??'')),0,5000),substr(trim((string)($_POST['emergency_name']??'')),0,150),substr(trim((string)($_POST['emergency_phone']??'')),0,80),$photo?:null,$licenseDoc?:null,$identityDoc?:null,$insuranceDoc?:null,substr(trim((string)($_POST['admin_notes']??'')),0,5000),$active,isset($_POST['featured'])?1:0,max(-9999,min(9999,(int)($_POST['sort_order']??100)))];
        if($id){$sql='UPDATE guides SET guide_code=?,status=?,first_name=?,last_name=?,display_name=?,email=?,phone=?,whatsapp=?,date_of_birth=?,gender=?,nationality=?,address=?,city=?,district=?,country=?,nic_passport=?,license_number=?,license_type=?,license_expiry=?,tourism_registration=?,years_experience=?,languages=?,service_regions=?,specializations=?,driver_guide=?,daily_rate=?,bio_de=?,bio_en=?,emergency_name=?,emergency_phone=?,photo_path=?,license_document_path=?,identity_document_path=?,insurance_document_path=?,admin_notes=?,active=?,featured=?,sort_order=? WHERE id=?';$values[]=$id;db()->prepare($sql)->execute($values);}else{$sql="INSERT INTO guides (guide_code,status,first_name,last_name,display_name,email,phone,whatsapp,date_of_birth,gender,nationality,address,city,district,country,nic_passport,license_number,license_type,license_expiry,tourism_registration,years_experience,languages,service_regions,specializations,driver_guide,daily_rate,bio_de,bio_en,emergency_name,emergency_phone,photo_path,license_document_path,identity_document_path,insurance_document_path,admin_notes,active,featured,sort_order,consent_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())";db()->prepare($sql)->execute($values);$id=(int)db()->lastInsertId();}
        flash('success','Reiseleiter wurde gespeichert.');redirect('admin/guide-edit.php?id='.$id);
    }catch(Throwable $exception){flash('error','Speichern fehlgeschlagen: '.$exception->getMessage());redirect('admin/guide-edit.php'.($id?'?id='.$id:''));}
}
$adminPage='guides';$adminTitle=$id?'Reiseleiter bearbeiten':'Reiseleiter anlegen';require __DIR__.'/_header.php';
?>
<div class="admin-content"><a class="back-admin" href="guides.php">← Reiseleiter</a><div class="page-heading compact"><div><p><?= e($guide['guide_code']?:'NEUES PROFIL') ?></p><h1><?= e($guide['display_name']?:'Reiseleiter anlegen') ?></h1><span>Profil, Verfügbarkeit, Preise und private Nachweise.</span></div></div>
<form class="editor-form" method="post" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$guide['id'] ?>">
<section class="admin-card form-card"><div class="card-head"><div><h2>Status & Profil</h2><p>Nur freigegebene und aktive Profile erscheinen im Reiseplaner.</p></div></div><div class="form-grid thirds">
<label>Guide-Code<input name="guide_code" value="<?= e($guide['guide_code']) ?>" maxlength="40" placeholder="wird automatisch erstellt"></label><label>Status<select name="status"><?php foreach(['pending'=>'Neu / Prüfung','approved'=>'Freigegeben','suspended'=>'Pausiert','rejected'=>'Abgelehnt'] as $value=>$label):?><option value="<?= e($value) ?>"<?= selected($value,$guide['status']) ?>><?= e($label) ?></option><?php endforeach;?></select></label><label>Sortierung<input name="sort_order" type="number" value="<?= (int)$guide['sort_order'] ?>"></label>
<label class="check"><input type="checkbox" name="active" value="1"<?= checked((bool)$guide['active']) ?>> Aktiv und im Planer auswählbar</label><label class="check"><input type="checkbox" name="featured" value="1"<?= checked((bool)$guide['featured']) ?>> Hervorgehoben</label>
<label>Profilfoto<input type="file" name="photo" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"></label><?php if($guide['photo_path']):?><div class="vehicle-admin-preview"><img class="guide-photo large" src="<?= e(url($guide['photo_path'])) ?>" alt=""><label class="check"><input type="checkbox" name="remove_photo"> Foto entfernen</label></div><?php endif;?>
</div></section>
<section class="admin-card form-card"><div class="card-head"><div><h2>Persönliche Angaben</h2></div></div><div class="form-grid thirds">
<label>Vorname *<input name="first_name" required value="<?= e($guide['first_name']) ?>"></label><label>Nachname *<input name="last_name" required value="<?= e($guide['last_name']) ?>"></label><label>Anzeigename<input name="display_name" value="<?= e($guide['display_name']) ?>"></label><label>E-Mail *<input name="email" type="email" required value="<?= e($guide['email']) ?>"></label><label>Telefon<input name="phone" value="<?= e($guide['phone']) ?>"></label><label>WhatsApp<input name="whatsapp" value="<?= e($guide['whatsapp']) ?>"></label><label>Geburtsdatum<input name="date_of_birth" type="date" value="<?= e((string)$guide['date_of_birth']) ?>"></label><label>Geschlecht<input name="gender" value="<?= e($guide['gender']) ?>"></label><label>Nationalität<input name="nationality" value="<?= e($guide['nationality']) ?>"></label><label>Ort<input name="city" value="<?= e($guide['city']) ?>"></label><label>Distrikt<input name="district" value="<?= e($guide['district']) ?>"></label><label>Land<input name="country" value="<?= e($guide['country']) ?>"></label><label class="span-two">Adresse<textarea name="address" rows="3"><?= e($guide['address']) ?></textarea></label><label>NIC / Reisepass<input name="nic_passport" value="<?= e($guide['nic_passport']) ?>"></label>
</div></section>
<section class="admin-card form-card"><div class="card-head"><div><h2>Qualifikation & Preis</h2></div></div><div class="form-grid thirds">
<label>Lizenznummer *<input name="license_number" required value="<?= e($guide['license_number']) ?>"></label><label>Lizenzart<input name="license_type" value="<?= e($guide['license_type']) ?>"></label><label>Gültig bis<input name="license_expiry" type="date" value="<?= e((string)$guide['license_expiry']) ?>"></label><label>Tourismus-Registrierung<input name="tourism_registration" value="<?= e($guide['tourism_registration']) ?>"></label><label>Erfahrung (Jahre)<input name="years_experience" type="number" min="0" max="70" value="<?= (int)$guide['years_experience'] ?>"></label><label>Tageshonorar (€)<input name="daily_rate" type="number" min="0" step="0.01" value="<?= e(number_format((float)$guide['daily_rate'],2,'.','')) ?>"></label><label class="check"><input type="checkbox" name="driver_guide" value="1"<?= checked((bool)$guide['driver_guide']) ?>> Driver-Guide</label><label class="span-two">Sprachen *<input name="languages" required value="<?= e($guide['languages']) ?>"></label><label class="span-two">Einsatzregionen<input name="service_regions" value="<?= e($guide['service_regions']) ?>"></label><label class="span-two">Spezialisierungen<input name="specializations" value="<?= e($guide['specializations']) ?>"></label><label class="span-two">Profil Deutsch<textarea name="bio_de" rows="4"><?= e($guide['bio_de']) ?></textarea></label><label class="span-two">Profil Englisch<textarea name="bio_en" rows="4"><?= e($guide['bio_en']) ?></textarea></label>
</div></section>
<section class="admin-card form-card"><div class="card-head"><div><h2>Private Nachweise & interne Angaben</h2><p>Dokumente werden geschützt gespeichert und nur über das Admin-Portal geöffnet.</p></div></div><div class="form-grid thirds">
<label>Lizenznachweis<input type="file" name="license_document" accept=".pdf,.jpg,.jpeg,.png"></label><label>Identitätsnachweis<input type="file" name="identity_document" accept=".pdf,.jpg,.jpeg,.png"></label><label>Versicherungsnachweis<input type="file" name="insurance_document" accept=".pdf,.jpg,.jpeg,.png"></label>
<div class="document-links span-two"><?php foreach(['license'=>'Lizenz','identity'=>'Identität','insurance'=>'Versicherung'] as $type=>$label):$key=$type.'_document_path';if(!$guide[$key])continue;?><a href="guide-document.php?id=<?= (int)$guide['id'] ?>&type=<?= e($type) ?>" target="_blank"><?= e($label) ?> öffnen ↗</a><?php endforeach;?></div>
<label>Notfallkontakt<input name="emergency_name" value="<?= e($guide['emergency_name']) ?>"></label><label>Notfalltelefon<input name="emergency_phone" value="<?= e($guide['emergency_phone']) ?>"></label><label class="span-two">Interne Notizen<textarea name="admin_notes" rows="4"><?= e($guide['admin_notes']) ?></textarea></label>
</div></section><div class="form-actions"><a href="guides.php">Abbrechen</a><button class="primary-button" type="submit">Reiseleiter speichern</button></div></form></div>
<?php require __DIR__.'/_footer.php'; ?>
