<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
require_admin_permission('hotels', request_is_post());
$id=max(0,(int)($_GET['id']??$_POST['id']??0));
$room=['id'=>0,'hotel_id'=>max(0,(int)($_GET['hotel_id']??$_POST['hotel_id']??0)),'code'=>'','name_de'=>'','name_en'=>'','description_de'=>'','description_en'=>'','bed_type_de'=>'','bed_type_en'=>'','amenities_de'=>'','amenities_en'=>'','base_rate_per_room_night'=>0,'standard_guests'=>2,'max_guests'=>3,'extra_bed_allowed'=>1,'extra_bed_percent'=>30,'child_percent'=>50,'room_size_sqm'=>0,'inventory'=>0,'image_path'=>'','featured'=>0,'active'=>1,'sort_order'=>10];
if($id){$stmt=db()->prepare('SELECT * FROM hotel_room_types WHERE id=?');$stmt->execute([$id]);$loaded=$stmt->fetch();if(!$loaded){flash('error','Zimmerkategorie wurde nicht gefunden.');redirect('admin/hotels.php');}$room=$loaded;}
$hotelStmt=db()->prepare("SELECT c.id,c.name_de,c.name_en,d.name_de AS destination_name FROM catalog_items c JOIN destinations d ON d.id=c.destination_id WHERE c.id=? AND c.type='accommodation'");$hotelStmt->execute([(int)$room['hotel_id']]);$hotel=$hotelStmt->fetch();if(!$hotel){flash('error','Hotel wurde nicht gefunden.');redirect('admin/hotels.php');}

if(request_is_post()){
    verify_csrf();$pdo=db();
    try{
        $code=strtolower(trim((string)($_POST['code']??'')));$code=trim((string)preg_replace('/[^a-z0-9]+/','-',$code),'-');
        $nameDe=substr(trim((string)($_POST['name_de']??'')),0,190);$nameEn=substr(trim((string)($_POST['name_en']??'')),0,190);
        if($code===''||$nameDe===''||$nameEn==='')throw new RuntimeException('Code sowie beide Zimmernamen sind erforderlich.');
        $image=isset($_POST['remove_image'])?'':upload_image($_FILES['image']??[],(string)$room['image_path']);
        $standardGuests=max(1,min(12,(int)($_POST['standard_guests']??2)));$extraBedAllowed=isset($_POST['extra_bed_allowed'])?1:0;$maximumGuests=$extraBedAllowed?max($standardGuests,min(12,(int)($_POST['max_guests']??3))):$standardGuests;
        $values=[(int)$room['hotel_id'],$code,$nameDe,$nameEn,trim((string)($_POST['description_de']??'')),trim((string)($_POST['description_en']??'')),substr(trim((string)($_POST['bed_type_de']??'')),0,120),substr(trim((string)($_POST['bed_type_en']??'')),0,120),trim((string)($_POST['amenities_de']??'')),trim((string)($_POST['amenities_en']??'')),max(0,(float)($_POST['base_rate']??0)),$standardGuests,$maximumGuests,$extraBedAllowed,max(0,min(100,(float)($_POST['extra_bed_percent']??30))),max(0,min(100,(float)($_POST['child_percent']??50))),max(0,min(1000,(int)($_POST['room_size_sqm']??0))),max(0,min(9999,(int)($_POST['inventory']??0))),$image,isset($_POST['featured'])?1:0,isset($_POST['active'])?1:0,(int)($_POST['sort_order']??10)];
        $pdo->beginTransaction();
        if($id){$values[]=$id;$pdo->prepare('UPDATE hotel_room_types SET hotel_id=?,code=?,name_de=?,name_en=?,description_de=?,description_en=?,bed_type_de=?,bed_type_en=?,amenities_de=?,amenities_en=?,base_rate_per_room_night=?,standard_guests=?,max_guests=?,extra_bed_allowed=?,extra_bed_percent=?,child_percent=?,room_size_sqm=?,inventory=?,image_path=?,featured=?,active=?,sort_order=? WHERE id=?')->execute($values);}
        else{$pdo->prepare('INSERT INTO hotel_room_types (hotel_id,code,name_de,name_en,description_de,description_en,bed_type_de,bed_type_en,amenities_de,amenities_en,base_rate_per_room_night,standard_guests,max_guests,extra_bed_allowed,extra_bed_percent,child_percent,room_size_sqm,inventory,image_path,featured,active,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($values);$id=(int)$pdo->lastInsertId();}
        $pdo->prepare('DELETE FROM hotel_room_rates WHERE room_type_id=?')->execute([$id]);
        $labelsDe=is_array($_POST['rate_label_de']??null)?$_POST['rate_label_de']:[];$labelsEn=is_array($_POST['rate_label_en']??null)?$_POST['rate_label_en']:[];$from=is_array($_POST['rate_from']??null)?$_POST['rate_from']:[];$to=is_array($_POST['rate_to']??null)?$_POST['rate_to']:[];$prices=is_array($_POST['rate_price']??null)?$_POST['rate_price']:[];$mins=is_array($_POST['rate_min_nights']??null)?$_POST['rate_min_nights']:[];
        $insert=$pdo->prepare('INSERT INTO hotel_room_rates (room_type_id,label_de,label_en,valid_from,valid_to,price_per_room_night,minimum_nights,active,sort_order) VALUES (?,?,?,?,?,?,?,1,?)');
        foreach($labelsDe as $i=>$labelDe){$labelDe=substr(trim((string)$labelDe),0,120);$labelEn=substr(trim((string)($labelsEn[$i]??'')),0,120);$price=max(0,(float)($prices[$i]??0));if($labelDe===''&&$labelEn===''&&$price<=0)continue;$fromDate=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($from[$i]??''))?$from[$i]:null;$toDate=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($to[$i]??''))?$to[$i]:null;if($fromDate&&$toDate&&$fromDate>$toDate)throw new RuntimeException('Bei einem Saisonpreis liegt das Bis-Datum vor dem Von-Datum.');$insert->execute([$id,$labelDe?:'Saisonpreis',$labelEn?:'Season rate',$fromDate,$toDate,$price,max(1,min(60,(int)($mins[$i]??1))),($i+1)*10]);}
        $pdo->commit();flash('success','Zimmerkategorie und Saisonpreise wurden gespeichert.');redirect('admin/room-edit.php?id='.$id);
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Speichern fehlgeschlagen: '.$e->getMessage());redirect('admin/room-edit.php'.($id?'?id='.$id:'?hotel_id='.(int)$room['hotel_id']));}
}
$rates=[];if($id){$rateStmt=db()->prepare('SELECT * FROM hotel_room_rates WHERE room_type_id=? ORDER BY sort_order,id');$rateStmt->execute([$id]);$rates=$rateStmt->fetchAll();}if(!$rates)$rates=[['label_de'=>'','label_en'=>'','valid_from'=>'','valid_to'=>'','price_per_room_night'=>'','minimum_nights'=>1]];
$adminPage='hotels';$adminTitle=$id?'Zimmer bearbeiten':'Neue Zimmerkategorie';require __DIR__.'/_header.php';
?>
<div class="admin-content narrow"><a class="back-admin" href="hotel-rooms.php?hotel_id=<?= (int)$hotel['id'] ?>">← <?= e($hotel['name_de']) ?></a><div class="page-heading compact"><div><p><?= e(strtoupper($hotel['destination_name'])) ?></p><h1><?= $id?'Zimmerkategorie bearbeiten':'Neue Zimmerkategorie' ?></h1><span>Zimmerpreis pro Zimmer und Nacht; Verpflegung wird separat pro Person berechnet.</span></div></div>
<form class="editor-form" method="post" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="hotel_id" value="<?= (int)$hotel['id'] ?>">
<section class="admin-card form-card"><div class="card-head"><div><h2>Zimmerdetails</h2><p>Deutsch & Englisch</p></div></div><div class="form-grid thirds"><label>Code<input name="code" required value="<?= e($room['code']) ?>" placeholder="deluxe-double"></label><label>Name Deutsch<input name="name_de" required value="<?= e($room['name_de']) ?>"></label><label>Name Englisch<input name="name_en" required value="<?= e($room['name_en']) ?>"></label><label>Betttyp Deutsch<input name="bed_type_de" value="<?= e($room['bed_type_de']) ?>"></label><label>Bed type English<input name="bed_type_en" value="<?= e($room['bed_type_en']) ?>"></label><label>Zimmergröße (m²)<input type="number" min="0" name="room_size_sqm" value="<?= (int)$room['room_size_sqm'] ?>"></label><label class="span-two">Beschreibung Deutsch<textarea name="description_de" rows="3"><?= e($room['description_de']) ?></textarea></label><label class="span-two">Description English<textarea name="description_en" rows="3"><?= e($room['description_en']) ?></textarea></label><label class="span-two">Ausstattung Deutsch<textarea name="amenities_de" rows="3" placeholder="Klimaanlage, Balkon, WLAN …"><?= e($room['amenities_de']) ?></textarea></label><label class="span-two">Amenities English<textarea name="amenities_en" rows="3"><?= e($room['amenities_en']) ?></textarea></label></div></section>
<section class="admin-card form-card"><div class="card-head"><div><h2>Preis & Belegung</h2><p>Der Basispreis gilt, wenn kein passender Saisonpreis vorhanden ist.</p></div></div><div class="form-grid thirds"><label>Basispreis / Zimmer / Nacht (€)<input type="number" min="0" step="0.01" name="base_rate" value="<?= e($room['base_rate_per_room_night']) ?>"></label><label>Standardgäste<input type="number" min="1" max="12" name="standard_guests" value="<?= (int)$room['standard_guests'] ?>"></label><label>Maximale Gäste<input type="number" min="1" max="12" name="max_guests" value="<?= (int)$room['max_guests'] ?>"></label><label class="check"><input type="checkbox" name="extra_bed_allowed" value="1"<?= checked((bool)$room['extra_bed_allowed']) ?>> Zusatzbett möglich</label><label>Zusatzbett Erwachsene (%)<input type="number" min="0" max="100" step="0.01" name="extra_bed_percent" value="<?= e($room['extra_bed_percent']) ?>"></label><label>Kinderpreis (%)<input type="number" min="0" max="100" step="0.01" name="child_percent" value="<?= e($room['child_percent']) ?>"></label><label>Verfügbare Zimmer<input type="number" min="0" name="inventory" value="<?= (int)$room['inventory'] ?>"><small>0 = Bestand nicht im System begrenzen</small></label><label>Sortierung<input type="number" name="sort_order" value="<?= (int)$room['sort_order'] ?>"></label><label class="check"><input type="checkbox" name="featured" value="1"<?= checked((bool)$room['featured']) ?>> Als Standard empfehlen</label><label class="check"><input type="checkbox" name="active" value="1"<?= checked((bool)$room['active']) ?>> Aktiv buchbar</label><label class="span-two">Zimmerbild<input type="file" name="image" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp"><?php if($room['image_path']):?><small>Aktuell: <?= e($room['image_path']) ?></small><span class="check"><input type="checkbox" name="remove_image" value="1"> Bild entfernen</span><?php endif;?></label></div></section>
<section class="admin-card form-card"><div class="card-head"><div><h2>Saisonpreise</h2><p>Datumsabhängige Preise und Mindestnächte</p></div><button class="secondary-button" type="button" data-add-rate>＋ Preiszeitraum</button></div><div class="room-rate-list" data-rate-list><?php foreach($rates as $rate):?><div class="room-rate-row"><label>Name Deutsch<input name="rate_label_de[]" value="<?= e($rate['label_de']) ?>"></label><label>Name Englisch<input name="rate_label_en[]" value="<?= e($rate['label_en']) ?>"></label><label>Von<input type="date" name="rate_from[]" value="<?= e((string)$rate['valid_from']) ?>"></label><label>Bis<input type="date" name="rate_to[]" value="<?= e((string)$rate['valid_to']) ?>"></label><label>Preis (€)<input type="number" min="0" step="0.01" name="rate_price[]" value="<?= e($rate['price_per_room_night']) ?>"></label><label>Min. Nächte<input type="number" min="1" max="60" name="rate_min_nights[]" value="<?= (int)$rate['minimum_nights'] ?>"></label><button type="button" data-remove-rate>Entfernen</button></div><?php endforeach;?></div></section>
<div class="form-actions"><a href="hotel-rooms.php?hotel_id=<?= (int)$hotel['id'] ?>">Abbrechen</a><button class="primary-button">Zimmer speichern</button></div></form></div>
<template id="rate-template"><div class="room-rate-row"><label>Name Deutsch<input name="rate_label_de[]"></label><label>Name Englisch<input name="rate_label_en[]"></label><label>Von<input type="date" name="rate_from[]"></label><label>Bis<input type="date" name="rate_to[]"></label><label>Preis (€)<input type="number" min="0" step="0.01" name="rate_price[]"></label><label>Min. Nächte<input type="number" min="1" max="60" name="rate_min_nights[]" value="1"></label><button type="button" data-remove-rate>Entfernen</button></div></template><script>(function(){var list=document.querySelector('[data-rate-list]'),tpl=document.getElementById('rate-template');document.querySelector('[data-add-rate]').addEventListener('click',function(){list.appendChild(tpl.content.cloneNode(true));});document.addEventListener('click',function(e){if(e.target.matches('[data-remove-rate]'))e.target.closest('.room-rate-row').remove();});})();</script>
<?php require __DIR__.'/_footer.php';?>
